### ISSUE TITLE
Flow error in subscription/mapAsyncIterator in 0.11.1

### ISSUE THREAD

**Issue by excitement-engineer** [graphql/graphql-js#1011]
I wanted to update to graphql@0.11.1. However, when I run the flow check in my codebase I get an error in `subscription/mapAsyncIterator` despite not using this function in my codebase. 

I am currently running flow@0.52.0. This is the output I am getting in my console:

<img width="857" alt="screen shot 2017-08-27 at 19 12 34" src="https://user-images.githubusercontent.com/19558321/29752324-2df2aa14-8b5c-11e7-8aad-0615acb05c95.png">

Anyone know if this is an issue with graphql-js?

**Comment by IvanGoncharov** [comment]
@excitement-engineer Yes this is an issue `graphql`.
Test for  `graphql` itself is passing since [.flowconfig](https://github.com/graphql/graphql-js/blob/master/.flowconfig) has:
```
[options]
experimental.const_params=true
```
As a tempory workaround, you can add the same thing to you `.flowconfig`.


@wincent @robzhu Code in question was added in #918, see [this code](https://github.com/graphql/graphql-js/commit/0779c36f9ba621d2d4a04539fec257cbbc5fe9e4#diff-5da861070d89e445a77546c3eacc5946R40).

It's exactly the same problem that blocks  update in `express-graphql` https://github.com/graphql/express-graphql/pull/383

I'm not sure why it's only affecting Node 7+.

**Comment by robzhu** [comment]
Thanks for filing this issue. This is definitely an issue with graphql-js and we'll work to get it fixed ASAP.

**Comment by wincent** [comment]
> I'm not sure why it's only affecting Node 7+.

I would have thought it's because we only run Flow on one Node version in order to speed up Travis runs, but it turns out that [we don't](https://github.com/graphql/express-graphql/blob/5f4e9a0cf1548a67db5dcaa622347c05c26fac44/.travis.yml) (in other repos, [we do](https://github.com/facebook/relay/blob/64d14b6e0cb9b00b9ddd663991beddf325123b98/.travis.yml)).

¯\\_(ツ)_/¯

**Comment by wincent** [comment]
Just cut v0.11.2 so going to close this.
