### ISSUE TITLE
Custom global fieldResolver called on introspection fields

### ISSUE THREAD

**Issue by southpolesteve** [graphql/graphql-js#1015]
Ran into this when adding a custom schema wide `fieldResolver`. This resolver will also get called for introspection fields which was surprising to me. Is this the expected behavior?

**Comment by growak** [comment]
I ran into the same issue, when launching the graphiql console.
@southpolesteve did you find a workaround or a way to fallback to the default fieldResolver ?

**Comment by growak** [comment]
@southpolesteve thx

**Comment by sibelius** [comment]
@southpolesteve can you share your solution?

can we close this?

**Comment by IvanGoncharov** [comment]
> Ran into this when adding a custom schema wide fieldResolver. This resolver will also get called for introspection fields which was surprising to me. Is this the expected behavior?

@southpolesteve @fredericnowak @sibelius It shouldn't work like that since field specific resolvers always take precedence over schema wide `fieldResolver`, see here:
https://github.com/graphql/graphql-js/blob/ae5b163d2e6c124107fa0971f6d838c8a7d29f51/src/execution/execute.js#L693
and all introspection types have assigned resolvers.

How did you construct your schema?
Did you use `new GraphQLSchema(`, `buildSchema` or something else?

Such behavior can occur if you construct your schema using `buildClientSchema` or similar function that doesn't use built-in introspections types.

**Comment by southpolesteve** [comment]
Sorry I no longer have access to the code where I solved this problem :/

**Comment by IvanGoncharov** [comment]
I did some testing and you were right. There are a few introspection fields that don't have resolver attached. So I created #1329 PR which should fix this issue.
