### ISSUE TITLE
CustomScalarType validation and GraphQLError handling

### ISSUE THREAD

**Issue by damianopetrungaro** [graphql/graphql-js#1142]
I am having a strange issue (or maybe it's just missing some documentation about it)

In this repo (few days ago) i was returning a GraphQLError when resolving a CustomScalarType if something went wrong and i retrieved the right error message by the playground client.
Here the "old" code
https://github.com/damianopetrungaro/graphql-node/commit/a9946a5df49845e80f80e1d0a29ed10b6339ac4c#diff-2878e9a978828e48f5975c2fa793fe64R153

After some code refactoring, the playground instead of showing the error correctly just show a 500 message with the unhandled Error it does not happen anymore:
https://github.com/damianopetrungaro/graphql-node/blob/master/api/src/usersContext/resolvers/index.js#L35

Any idea where i am wrong, or this is an issue by a new version?

- For test it just docker-compose up and go to the playground (http://localhost:3000/playground ) once everything is up and running.

The query for see the differences is:

```
mutation {
  createUser(name: "John", surname: "Wally", age: 1000) {
    id
    name
    surname
    age
  }
}

```
For "old" version: git checkout a9946a5 
For refactored version: git checkout master

**Comment by leebyron** [comment]
Sorry for the delay getting to this, but it looks like your master branch has moved considerably since you opened this.

Some general feedback from looking at the code, you shouldn't need a try/catch/return pattern, just allow the error to be thrown.

I also suggest ensuring you're using the latest version of this library, since the most recently released version fixed some issues with handling errors from custom scalars.

**Comment by damianopetrungaro** [comment]
@leebyron i confirm that a lot of issues has been fixed, now i can throw error as i were doing before the library started to have strange behaviours
