### ISSUE TITLE
Help needed on Graphql objects

### ISSUE THREAD

**Issue by fdelacruzsoto** [graphql/graphql-js#1260]
If I have  `var obj = { name: 'Bill', ... etc}` and a GraphQLObjectType like  `const Person = new GraphQLObjectType({name: 'person', fields: { ...some fields with graphql types ... }});`

How do I get a hydrated GraphQL object like the ones that are returned from the server:  `{ name 'Bill', age: null, __typename: 'Person' }`

Note: I need to get this object on the server.

**Comment by IvanGoncharov** [comment]
@fdelacruzsoto Not sure that I fully understand your question, but here is a good example of how you should register field resolvers: http://graphql.org/graphql-js/object-types/

Also please note that issue in this repo are intended for reporting issues and feature requests so it's better to ask questions on the StackOverflow:
https://github.com/graphql/graphql-js/blob/master/.github/ISSUE_TEMPLATE.md#questions-regarding-how-to-use-graphql

**Comment by thataustin** [comment]
Actually, that's a pretty good question regarding the documentation.  I've noticed that the resolvers will take a normal JS object and a GraphQL return type and then fill in any missing fields and add the __typename. 

I'm not sure about that mechanics of how they do that, but I think it would be pretty cool to have some documentation to how how to go from a POJO + GraphQLObjectType to get the sort of object that is returned via queries/mutations/subscriptions.

This especially makes sense for those that have been struggling to use services like Pusher instead of graphql subscriptions.  I've seen a lot of chatter about that.  I imagine that being able to create valid GraphQL objects would allow you to just publish things over Pusher / Pubnub etc, and that would alleviate some of those pains for people that already have those types of `ws` implementations.

**Comment by IvanGoncharov** [comment]
@thataustin I still suggest to discussing such issues on StackOverflow. Since after this issue is closed it would be impossible to find. So it doesn't benefit GraphQL community as Stackoverflow question would.

>I'm not sure about that mechanics of how they do that, but I think it would be pretty cool to have some documentation to how how to go from a POJO + GraphQLObjectType to get the sort of object that is returned via queries/mutations/subscriptions.

It's documented in the spec http://facebook.github.io/graphql/October2016/#sec-Executing-Selection-Sets
And implemented here:
https://github.com/graphql/graphql-js/blob/499a75939f70c4863d44149371d6a99d57ff7c35/src/execution/execute.js#L498-L502

> This especially makes sense for those that have been struggling to use services like Pusher instead of graphql subscriptions. I've seen a lot of chatter about that. I imagine that being able to create valid GraphQL objects would allow you to just publish things over Pusher / Pubnub etc, and that would alleviate some of those pains for people that already have those types of ws implementations.

GraphQL subscription is a transport-agnostic mechanism and it doesn't have any connection to WS. You probably referring to Apollo specific of GraphQL Subscriptions over WS which is just a wrapper around `subscribe` function. So you can use the exact same function to implement your own transport protocol.

https://github.com/graphql/graphql-js/blob/499a75939f70c4863d44149371d6a99d57ff7c35/src/subscription/subscribe.js#L33-L53

**Comment by leebyron** [comment]
Closing this issue - please keep issues for bug reports and move questions to stack overflow where they can build up a corpus of knowledge over time.

**Comment by thataustin** [comment]
@leebyron / @IvanGoncharov - I'm not sure why documentation shouldn't live with the code though.  Why is SO inherently better than Github?  

Stackoverflow doesn't even have data available regarding which version of which repo an issue was filed against.  At least in Github you are in the right context to do that research.  

SO is not an idea place for library documentation.  Can't tell you how many links I find issues to problems that have been fixed by more recent versions of a library that are out of date on SO - and you have to end up in Github anyway to figure that out.   The real corpus of knowledge should be in library documentation.  The fact that someone can't figure out how to use a function in this repo doesn't mean SO is at fault.  I believe it means the documentation over here is not particularly conducive to learning / using the great tool ya'll are making.  You can certainly run your repo how you'd like, no problems there, just offering up my little opinion, based on years of researching in both platforms :-)

**Comment by leebyron** [comment]
I agree with you, documentation is important! More than happy to consider PRs which improve the documentation in this repo.

We encourage general questions on Stack Overflow since once answered they are easily searchable and it keeps github issues focused on actionable bugs and improvements
