### ISSUE TITLE
Server should skip validation of queries with include===false/skip===true

### ISSUE THREAD

**Issue by MatthewHerbst** [graphql/graphql-js#1334]
Currently, the server validates all parts of a query, even parts that will be dropped due to `include` being `false` or `skip` being `true`.

For example:

```
contacts(
  # This argument is a String! in our schema
  uid: $loggedInUserUid
) @include(if: $profileIsLoggedIn) {
  ...
}
```

In the above scenario, if the user is not logged in, then the `loggedInUserUid` will be `null` since there is no profile to pull a uid from. However, sending the above with `null` to the server will cause a validation error since the `uid` argument is not nullable.

A quick fix of course would be to make the `uid` field nullable. However, that seriously harms schema design, since the query is not possible without a `uid`.

Would it be possible for the server to skip validation of parts of queries that it knows will not be included?

This question comes out of discussion from https://github.com/facebook/relay/issues/1791

**Comment by IvanGoncharov** [comment]
> Would it be possible for the server to skip validation of parts of queries that it knows will not be included?

@MatthewHerbst It's impossible according to GraphQL design:
> Typically validation is performed in the context of a request immediately before execution, however a GraphQL service may execute a request without explicitly validating it if that exact same request is known to have been validated before. For example: the request may be validated during development, provided it does not later change, or a service may validate a request once and memoize the result to avoid validating the same request again in the future. Any client‐side or development‐time tool should report validation errors and not allow the formulation or execution of requests known to be invalid at that given point in time.

http://facebook.github.io/graphql/draft/#sec-Validation

If validation process will depend on query variables it will be imposible to validate quires during build time, e.g. `eslint-graphql` or validate submitted persistent queries.

> A quick fix of course would be to make the uid field nullable. However, that seriously harms schema design, since the query is not possible without a uid.

You can create top-level `viewer` field simular to how it's done in GitHub API:
https://developer.github.com/v4/query/#viewer

**Comment by MatthewHerbst** [comment]
> You can create top-level `viewer` field...

We have a top-level viewer. Not sure I follow how that helps the issue at hand?

[Section 3.13](https://facebook.github.io/graphql/draft/#sec-Type-System.Directives) of the GraphQL spec says (bolding mine):

> A GraphQL schema describes directives which are used to annotate various parts of a GraphQL document *as an indicator that they should be evaluated differently by a validator*, executor, or client tool such as a code generator.

To me that seems that there is actually flexibility here, and that it would be perfectly valid to not validate part of a query based on a directive.

As to having tools being able to validate queries based on directives, I don't think this change would make it any harder. The tool would simply assume that the part of the query will be evaluated, and so it validates it. If that part of the query ends up not being evaluated by the server, there is no harm there.

**Comment by IvanGoncharov** [comment]
> Meaning not always...

Meaning it should be possible to validate the query without executing it for example in build time.

> as an indicator that they should be evaluated differently by a validator

Yes you are absolutely right directive can change validation but values for query variables shouldn't be required during validation.

> The tool would simply assume that the part of the query will be evaluated (so it assumes all includes are true and all skips are false), and so it validates it. If that part of the query ends up not being evaluated by the server, there is no harm there.

Which is exactly what happing at the moment, GraphQL assumes that your query is:
```
query ($loggedInUserUid: String!) {
  contacts(uid: $loggedInUserUid)
  ...
}
```
And that's why it required to for you to specify `$loggedInUserUid` type as `String!`. So when you send `loggedInUserUid` value to a server it's validated against `String!` and `null` doesn't pass this check.

> We have a top-level viewer. Not sure I follow how that helps the issue at hand?

So it would be logical to have ability to write query like that:
```
query ($profileIsLoggedIn: Boolean!) {
  viewer @include(if: $profileIsLoggedIn) {
    contacts
  }
}
```

**Comment by IvanGoncharov** [comment]
> The way we have written it as current is certainly less correct than what you propose, but it is still "correct"

@MatthewHerbst Fully agree. `viewer` concept is not a part of GraphQL specification and just one of many best practices. So your schema perfectly valid without it.

However, you getting validation error not for a schema itself but for a particular query written against it.

> The server could choose to skip validation of parts of the query with the directive, since it knows the values passed to the variables (something the lint tools do not know).

GraphQL query is strong-typed so when you defined your query you explicitly specified that `loggedInUserUid` is non-null so server checks it's actual value according to its definition and rejects `null` value.

------
To be sure that I 100% correctly understand your problem can you share the full query?
Because your initial post have only `contacts` field and I don't see how `loggedInUserUid` and `profileIsLoggedIn` defined.
Also please share exact error you are getting from `graphql-js`.

------
Assuming your query looks simular to this one:
```qraphql
query getProfileInfo($profileIsLoggedIn: Boolean!, $loggedInUserUid: ID!) {
  contacts(uid: $loggedInUserUid) @include(if: $profileIsLoggedIn) {
    ...
  }
}
```

I will use Flow for this analogy but same is true for any strong-typed programming language:
```flow
function getProfileInfo(profileIsLoggedIn: boolean, loggedInUserUid: string) {
  if (profileIsLoggedIn) {
    return getContacts(loggedInUserUid)
  }
}

function getContacts(uid: string) {
  // ...
}
```
And when you call it like that:
```flow
getProfileInfo(false)
```

You will get this error:
```
11: getProfileInfo(false)
    ^ Cannot call `getProfileInfo` because function [1] requires another argument.
References:
1: function getProfileInfo(profileIsLoggedIn: boolean, loggedInUserUid: string) {
   ^ [1]
```

Same is true for TS, C++, Java or any other strong-typed programming language.
It's because function definition validated separately from it's invocation.

-----

As a workaround you can use default value feature:
```graphql
query getProfileInfo($profileIsLoggedIn: Boolean!, $loggedInUserUid: ID = 'NotAnID') {
  contacts(uid: $loggedInUserUid) @include(if: $profileIsLoggedIn) {
    ...
  }
}
```
So you can call it with: `{ profileIsLoggedIn: false }`

**Comment by MatthewHerbst** [comment]
Yeah, default values I think are what we might end up doing.

> It's because function definition [is] validated separately from its invocation.

I think that's the crux of what I'm trying to get at: does it striclty need to be in GraphQL's case?

Will be traveling for the next week. Will post full query/error when I get back if the team hasn't come up with some other solution by then (for now we split the queries until we find a better solution). Thanks for the continued thoughts/learning/fast replies.

**Comment by MatthewHerbst** [comment]
Alright, so here is our query, with the error messages from the GraphQL server:

(Note that I've removed the non-relevant fields from the query, so the below is only the relevant part of the query to this concern.)
```
graphql`
  query SomeQuery(
    $fetchComparerProfile: Boolean!,
    $compareKey: String!,
  ) {
    viewer {
      currentProfile {
        alignmentByProfileKey (profileKey: $compareKey) @include (if: $fetchComparerProfile) {
          ...
        }
      }
    }
  }
`;
```

In this scenario, if `fetchComparerProfile` is `false`, then we expect `compareKey` to be `null`, since the setting of `fetchComparerProfile` is based on the existence of `compareKey` in the url.

The error from the GraphQL server is:

```
GraphQLError: Variable "$compareKey" got invalid value null; Expected non-nullable type String! not to be null.
    at coercionError (/src/node_modules/graphql/utilities/coerceValue.js:179:10)
    at coerceValue (/src/node_modules/graphql/utilities/coerceValue.js:53:24)
    at getVariableValues (/src/node_modules/graphql/execution/values.js:74:53)
    at buildExecutionContext (/src/node_modules/graphql/execution/execute.js:246:63)
    at executeImpl (/src/node_modules/graphql/execution/execute.js:140:17)
    at Object.execute (/src/node_modules/graphql/execution/execute.js:131:229)
    at doRunQuery (/src/node_modules/apollo-server-core/dist/runQuery.js:122:42)
    at /src/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Relay compiles the above query no problem, since it's valid at compile-time as no values have been put into it yet. It's only at runtime that the server spits out the error (and Relay also dumps a warning). Relay and other static tools can continue doing what they do now at built time, and we could allow the server to be a little smarter at run time. Maybe the server could drop a warning at runtime for an invalid sub-query within a directive that isn't used, but given a proper directive, we hope that it shouldn't completely fail if the sub-query within the directive isn't used.

**Comment by IvanGoncharov** [comment]
@MatthewHerbst Thanks for posting your query and error, now I'm 100% sure we are on the same page. 

> Maybe the server could drop a warning at runtime for an invalid sub-query within a directive that isn't used, but given a proper directive, we hope that it shouldn't completely fail if the sub-query within the directive isn't used.

In your case query variables are validated against:
```
  query SomeQuery(
    $fetchComparerProfile: Boolean!,
    $compareKey: String!,
  ) {
```
It's like you announced contract for acceptable query variables but allowed to break it in some case.
See my function example from: https://github.com/graphql/graphql-js/issues/1334#issuecomment-387946539

On purely practical side it will affect perfomance since you need to validate query variables not once per query but once per usage.

-----
Anyway `graphql-js` is correct according to the current specfication. If you think specification should be change please open an issue here:
https://github.com/facebook/graphql/issues/new

**Comment by IvanGoncharov** [comment]
@MatthewHerbst I forget to specify part of the spec that requires `graphql-js` to produce an error:
> Otherwise if variableType is a Non‐Nullable type, and either hasValue is not true or value is null, throw a query error.

http://facebook.github.io/graphql/draft/#sec-Coercing-Variable-Values
