### ISSUE TITLE
about mutation problem

### ISSUE THREAD

**Issue by z3214965** [graphql/graphql-js#1351]
my code：
```js
let mutationString = `mutation{addUser(id:"1"){ id }}`;

const Mutation = new GraphQLObjectType({
  name: 'Mutations',
  description: '变更集合',
  fields: {
    addUser: {
      type: GraphQLString,
      description: '添加用户信息',
      args: {
        id: {
          type: GraphQLString
        }
      },
      async resolve(source, { id }) {
        return "test";
      }
    }
  }
});

const schema = new GraphQLSchema({
  query: Query,
  mutation: Mutation
});
```
```
error message:"Field "addUser" must not have a selection since type "String" has no subfields."
```

I do not know why？

**Comment by IvanGoncharov** [comment]
@z3214965 In your code `addUser` returns `type: GraphQLString` but in your query you expect it to object with `id` field.
You should rewrite your query as:
```
mutation {
  addUser(id: 1)
}
```

**Comment by z3214965** [comment]
mutation {
  createMessage(input: {
    author: "andy",
    content: "hope is a good thing",
  }) {
    id
  }
}
this is official tutorial，why return id ？

**Comment by IvanGoncharov** [comment]
@z3214965 Because `createMessage` returns `Message` not a `String`:
```
createMessage(input: MessageInput): Message
```

Please use StackOverflow for questions regarding how to use GraphQL:
> We want to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track bugs and features that affect development.
If you have a question on how to use GraphQL, please post it to Stack Overflow with the tag #graphql. Please do not post general questions directly as GitHub issues. They may sit for weeks unanswered, or may be spontaneously closed without answer.

**Comment by z3214965** [comment]
I understand, thank you very much
