### ISSUE TITLE
Parser/Lexer error with an empty query type

### ISSUE THREAD

**Issue by yellowiscool** [graphql/graphql-js#1495]
Hei,

I have a very simple schema with only mutations. The server library I use requires a query type to be defined, so I defined an empty Query type.

This is my very simple schema:
```
type Query {}
```

And the error when I try to parse it:

```
V:\whatever\node_modules\graphql\language\parser.js:1299
  throw (0, _error.syntaxError)(lexer.source, token.start, 'Expected ' + kind + ', found ' + (0, _lexer.getTokenDesc)(token));
  ^
Syntax Error: Expected Name, found }

GraphQL request (1:13)
1: type Query {}
```

GraphQL Version : 0.13.2

**Comment by yellowiscool** [comment]
Probably related to #937

**Comment by IvanGoncharov** [comment]
@yellowiscool It's expected behaviour.
You can pass parsing stage by omitting curly brackets `type Query` but you GraphQL still errors if you try to execute queries against such schema.

As Lee pointed our #937 is fixed: https://github.com/graphql/graphql-js/issues/937#issuecomment-349887736

The fixing problem that you describe requires changes to GraphQL Specification and actively disscussed here: https://github.com/facebook/graphql/issues/490
