### ISSUE TITLE
Introspection must provide input type for arguments

### ISSUE THREAD

**Issue by davide-ganito** [graphql/graphql-js#151]
Hello everyone!
Can somebody tell me the meaning of [this](https://github.com/graphql/graphql-js/blob/ef2073245f4366a116be7cf20b821cdf2127a745/src/utilities/buildClientSchema.js#L137) error?

Thank!

**Comment by dschafer** [comment]
It's tough to say without seeing a full stack trace, but it's possible that you're using a `GraphQLObjectType` as the type of an input argument, rather than a `GraphQLInputObjectType`; http://facebook.github.io/graphql/#sec-Input-Objects explains why object types are disallowed as the types of arguments and why input objects are used instead.

**Comment by dschafer** [comment]
Based on https://github.com/facebook/relay/issues/159, sounds like this is resolved.

**Comment by davide-ganito** [comment]
Yes, it is. Thx!

**Comment by felipellrocha** [comment]
Is the link above broken (the documentation one)? It doesn't send us anywhere, and I'm running into this same issue
