### ISSUE TITLE
Description when print a AST graphql object

### ISSUE THREAD

**Issue by amian84** [graphql/graphql-js#1521]
Hi, currently I've parsing a graphQL schema with parse function to AST object. Later I split the schema into different array of object to store into different files, one per type (interface, object type, enums...).

When I print the partial AST object to string again, this function avoid the descriptions attribute.. Then I lost all schema description. There are any solution for that or maybe this will be implement as new feature?

Example:
type Object1{
 #description of attribute att1
 att1: String
}

When print the AST object I lost descriptions
type Object1{
 att1: String
}

**Comment by IvanGoncharov** [comment]
@amian84 You are using legacy SDL syntax. You should use standard syntax for descriptions:
```graphql
type Object1{
  """description of attribute att1"""
  att1: String
}
```
In that case, description would be preserved in `print` output.

**Comment by amian84** [comment]
Hi @IvanGoncharov , i'm trying with the standard syntax as you commented me. But the parser fails when trying parse the description

const graphqllang= require('graphql/language');
 var test= graphqllang.parse(`type Test{
        """Description"""
        a:String
    }`);
/home/damian/Projects/graphql-mocker/node_modules/graphql/language/parser.js:972
  throw (0, _error.syntaxError)(lexer.source, token.start, 'Expected ' + kind + ', found ' + (0, _lexer.getTokenDesc)(token));
  ^
GraphQLError: Syntax Error GraphQL request (2:9) Expected Name, found String
1: type Test{
2:         """Description"""
           ^
3:         a:String

**Comment by IvanGoncharov** [comment]
@amian84 It looks like you are using `graphql-js` pre `0.12.0`.
Please run `npm ls graphql` and if it so update it.

**Comment by IvanGoncharov** [comment]
@amian84 It's tracked here: https://github.com/APIs-guru/graphql-faker/issues/41

**Comment by stephenh** [comment]
Well shoot, I'd been using `# ...` comments for ~year or so now and had never seen this other official syntax. That's cool.

Although fwiw we have places in our SDL files that should be the "quote-comments" (so moving our comments over to those) but we also have other places that are just commenting out "dead code", i.e.:

```graphql
type Foo { ... }

# old code
# asdf
# asdf

" Bar. "
type Bar { ... }
```
 
I'm trying to write a tool that loads `.graphql` files, makes a change, and saves it back, i.e. similar to Jest's `toMatchInlineSnapshot`.

However, the `# old code ...` comments disappear from the output with `print`.

For expediency, I'll probably just convert these `# old code` comments over to descriptions, but FWIW they are probably better left as "not associated to a type" comment nodes in the AST (because ^ I don't mean for them to be associated with the following `type Bar` node), that ideally would not be dropped and still output so that the `parse` + `print` cycle doesn't have any side-effects.

**Comment by danielrearden** [comment]
@stephenh This is definitely something we want to add in the near future. Please see [this issue](https://github.com/graphql/graphql-js/issues/2241) for more context and a possible workaround.

**Comment by stephenh** [comment]
@danielrearden oh great! My fault for not seeing that newer issue. :-) Thanks for the quick response!
