### ISSUE TITLE
Feature request: accept AST query in graphql()?

### ISSUE THREAD

**Issue by olalonde** [graphql/graphql-js#1564]
```javascript
import schema from './';
import gql from 'graphql-tag';
import { graphql } from 'graphql';

test('root graphql query', async () => {
  const r = await graphql(schema, gql`query { hello }`);
  expect(r.data).toEqual({ hello: 'Hello world!' });
});
```

It would be nice if an AST could be passed instead of a string for the `query` argument of graphql(). My editor (vim) does GraphQL syntax highlighting whenever I use the `gql` tag :O

**Comment by IvanGoncharov** [comment]
@olalonde Sorry for delay.

> My editor (vim) does GraphQL syntax highlighting whenever I use the gql tag :O

Thanks for describing your use case 👍 
Many editors highlight strings with `/* GraphQL */` prefix, see this thread:
https://github.com/apollographql/apollo-tooling/issues/724
Also you can dummy tags (e.g. [fake-tag](https://github.com/jaydenseric/fake-tag)).


> It would be nice if an AST could be passed instead of a string for the query argument of graphql().

`graphql` is a very simple function that just wrap a few other functions, if you want you can call every function separately (they all belongs to public API) or write your own version of `graphql`:
https://github.com/graphql/graphql-js/blob/7dd2b2bed841b9fd0c40c328826363ec79cc65c4/src/graphql.js#L180-L208


P.S. Since your are using it for tests please consider that `graphql-tag` do pretty advance stuff with your query beyound just running `parse` on it:
https://github.com/apollographql/graphql-tag/blob/master/src/index.js
