### ISSUE TITLE
[Proposal] Add `addField` method for object type

### ISSUE THREAD

**Issue by pd4d10** [graphql/graphql-js#1774]
Currently there seems no way to manipulate existing object types. It would be handy to have `addField` method as follows:

```js
const objType = new GraphQLObjectType({
  name: 'SomeObject',
  fields: {},
});

objType.addField('add', { name: 'add', type: GraphQLInt });

objType.getFields()
// {
//   add: { name: 'add', type: GraphQLInt },
// );
```

**Comment by IvanGoncharov** [comment]
@pd4d10 All `GraphQL*Type` are immutable, meaning you can't change them after creation.
So we can't add 'addField` or any other function that mutate instance of `GraphQLObjectType`.
Can you please share your use case?
Why you need `addField` function?

**Comment by pd4d10** [comment]
Thanks for the quick reply.

The current use case is, GraphQL types are generated at runtime from some other IDL, like Thrift or Protobuf. Sometimes it is not exactly we want. So I'm thinking a way to do some tweak based on it.

It is also inspired by graphql-go:
https://github.com/graphql-go/graphql/blob/a5c80ac140e28c006805b9fdc77bc54160ccb3f8/definition.go#L402

**Comment by pd4d10** [comment]
Since types are immutable by design, I guess the best practice is to manipulate `schema.graphql` and then generate types from schema again?

**Comment by IvanGoncharov** [comment]
@pd4d10 We are working on the new `transformSchema` function specifically designed for this use case. As one of the steps toward this goal, we added `toConfig` method to every `GraphQL*Type` class. 
So you can do:
```js
const config = objType.toConfig();
const modifiedType = new GraphQLObjectType({
  ...config,
  fields: {
    ...config.fields,
    add: { type: GraphQLInt },
  },
});
```

But please note that other types can reference old type object so you need to also update them to point to modified type. Also, note that `GraphQLSchema` is also designed to be immutable. Here is a complete example of how to properly use `toConfig`:
https://github.com/graphql/graphql-js/blob/master/src/utilities/lexicographicSortSchema.js

It's pretty low-level API and it's hard to use it directly that's why we working on adding more high-level `transformSchema` API.

Meanwhile, you can use external packages for schema manipulation, e.g. [graphql-compose](https://github.com/graphql-compose/graphql-compose).

I'm closing this issue since it will be fixed by `transformSchema` that is tracked under #1199
