### ISSUE TITLE
how to handle whitespace in Schema types?

### ISSUE THREAD

**Issue by zeeshanaligold** [graphql/graphql-js#1788]
![fixes](https://user-images.githubusercontent.com/26404433/54239570-5b624800-453d-11e9-8c32-9db601cd202c.png)

**Comment by IvanGoncharov** [comment]
> how to handle whitespace in Schema types?

@zeeshanaligold Short answer: You can't have whitespaces in graphql names.
Long answer: https://facebook.github.io/graphql/June2018/#sec-Names

P.S. You can always replace space with underscore `Start_Date`.

**Comment by zeeshanaligold** [comment]
I know but i can't replace it with underscore because i'm using stored procedure & can't have the access to update it.

**Comment by carlosen14** [comment]
what about space in ENUM type name? 
```js
const episodeEnum = new GraphQLEnumType({
  name: 'Episode',
  description: 'One of the films in the Star Wars Trilogy',
  values: {
    NEW HOPE: { // <<<<<<<<<<<<< like this
      value: 4,
      description: 'Released in 1977.',
    },
    'OLD HOPE': { // <<<<<<<<<<<<< or this? How to use it in query if you have to put the enum type without quotes
      value: 4,
      description: 'Released in 1977.',
    }
  },
});
```

**Comment by mjmahone** [comment]
@zeeshanaligold if you have business limitations that make it impossible to follow the spec, then you'll probably need to fork graphql-js, because you're already forking GraphQL the language. graphql-js is specifically meant to be a spec-compliant implementation that you can, but don't need to, use to work with GraphQL the language.
