### ISSUE TITLE
Convert arbitrary scalars to AST.

### ISSUE THREAD

**Issue by anhldbk** [graphql/graphql-js#1815]
Hi guys,

I'm trying to make a configuration language based on GraphQL (so I don't have write lexer/parser on my own). I want to support JSON as an input type by using `graphql-type-json`. But I've got an issue of parsing AST as described by this issue https://github.com/taion/graphql-type-json/issues/73.

@taion tell me that 

> That utility function (astFromValue) doesn't support converting arbitrary scalars to AST

I've found a hack to overcome the issue. Should I make a PR against this one?

**Comment by IvanGoncharov** [comment]
@anhldbk That's why we implemented `valueFromASTUntyped`
https://github.com/graphql/graphql-js/blob/8aef229cb29031eb475e3d647ad94c8d19b72461/src/utilities/valueFromASTUntyped.js#L18-L36

Moreover it's used by default:
https://github.com/graphql/graphql-js/blob/8aef229cb29031eb475e3d647ad94c8d19b72461/src/type/definition.js#L563

So you don't need to use package for it just do:
```js
 GraphQLScalarType({
  name: 'JSON',
  serialize: (value) => value,
});
```

**Comment by anhldbk** [comment]
@IvanGoncharov Thank you!

**Comment by anhldbk** [comment]
@IvanGoncharov Thank you for your hint. 

But would you please tell me how to properly parse JSON-enabled value into AST? I have to patch `astFromValue`: https://github.com/graphql/graphql-js/blob/8aef229cb2/src/utilities/astFromValue.js#L139-L140

by adding following lines before L139

```javascript

if (typeof serialized === 'object' ){
    return {
      kind: _kinds.Kind.OBJECT,
      value: serialized
    };
}

```

**Comment by IvanGoncharov** [comment]
@anhldbk Yes, it looks like a bug. We should support scalars that are serialized to complex values.
Can you please open a separate issue for that?
