### ISSUE TITLE
Int in Spec vs Implementation 

### ISSUE THREAD

**Issue by andimarek** [graphql/graphql-js#182]
Hi,

the spec says Int is a 32 bit value (http://facebook.github.io/graphql/#sec-Int) but the implementation allows much larger values (https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L32).

This seems wrong ... or do I miss something?

Thanks,
Andi

**Comment by OlegIlyenko** [comment]
+1 I was also concerned about this: https://github.com/facebook/graphql/issues/73#issuecomment-129445213

**Comment by leebyron** [comment]
You're correct that they currently differ. There are a couple of ways to resolve this, I'm not sure what is best and could use input from the community and @dschafer.

I think there are two perspectives: one is a desire to spec Int in a lowest-common denominator way such that servers and clients can all agree on a representation. Another perspective is to be more lenient and allow various transports to define this kind of limitation for themselves.

**A)** Change graphql-js Int implementation to restrict to signed 32-bit range.

This is probably the simplest fix, but it may cause issues for anyone currently using Int with numbers above 32-bit.

**B)** Change the spec to describe Int as 52-bit.

This would preserve any current usage of larger Ints and would assume clients would actually store them as Long or Doubles.

**C)** Change the spec to not describe any size for Int

Leaves Int size up to the implementation of various services. Perhaps puts burden on client interoperability but is the least restrictive to server implementations.

**Comment by OlegIlyenko** [comment]
Thanks for confirming this. My vote goes to solution **A**. The reason for this is because I see scalar type as a protocol or contract between server and client. I also described it in more detail [here](https://github.com/facebook/graphql/issues/73#issuecomment-129270745). I feel that solution **C** would not be very useful, especially when it comes to generic tools that are written against GraphQL spec and not concrete implementation of it - they generally can't make any assumptions about the concrete implementation. This will also introduce tighter coupling between client and concrete GraphQL server.

I also not in favour of solution **B** since I find 52-bit integer pretty incommon. The only language/platform that uses 52-bit integers (to my knowledge) is javascript. That said, if we look at present the future of the language, we will find that [asm.js defines int as a 32-bit integer value](http://asmjs.org/spec/latest/#int). WebAssemply also defines [i32 and i64 as 32-bit and 64-bit integers respectively](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#local-types). As far as I can tell, the es7 can also get [an `int32` scalar in typed objects](https://github.com/dslomov/typed-objects-es7). Since GraphQL is pretty young spec, I feel that it would be a good investment to consider these developments in javascript world.

**Comment by andimarek** [comment]
I also currently vote  for __A__. 

I don't think option __C__ is useful: It would make building compatible graphql implementations much more complicated. 
(This is not totally theoretical. The only thing I needed to change to make the todo app relay example work with an graphql-java backend, was this line https://github.com/andimarek/todomvc-relay-java/blob/master/app/js/components/TodoApp.js#L63 ... The 'first' Parameter was an Number > 2^31)

Solution __B__ is interesting, because I think every language is able to store 52 bit numbers in some kind. This would make using and implementing a server a bit more complicated. But the upside would be a more compatible server landscape, as not everybody has to implement some kind of Long.

Of course a modified __A__ is to add a real long datatype to the graphql language itself.

**Comment by leebyron** [comment]
Closing this now with option A as discussed here. Thanks again for the helpful discussion.
