### ISSUE TITLE
isDeprecated doesn't seem to work

### ISSUE THREAD

**Issue by enriquecaballero** [graphql/graphql-js#185]
Either I'm doing something wrong of isDeprecated isn't working...  This is what my type looks like:
```
const Employee = new GraphQLObjectType ({
  name: 'Employee',
  description: 'An Employee',
  fields: () => ({
    emp_no: {
      type: GraphQLInt,
      description: 'Employee Number',
      isDeprecated: true,
      resolve: (object) => object.emp_no
    },
  })
});
```
However, when I do introspection as such:
```
curl -XPOST -H "Content-Type:application/graphql" -d 'query TestQuery { __type (name: "Employee") { fields { name, description, isDeprecated} } }' http://localhost:3000/graphql
```
My response has all fields with ```isDeprecated: false```

Am I defining my GraphQLObjectType field incorrectly?

**Comment by dschafer** [comment]
`isDeprecated` is a derived field in the introspection; when defining a field, a `deprecationReason` can be provided. `isDeprecated` will be set to true iff that reason is set.

https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L475
https://github.com/graphql/graphql-js/blob/master/src/type/introspection.js#L203

**Comment by leebyron** [comment]
Since this is an easy pitfall to encounter, I just added some early errors to help detect and advise.
