### ISSUE TITLE
Build resolveInfo manually

### ISSUE THREAD

**Issue by marusapur** [graphql/graphql-js#2029]
Hello! How can i build GraphQLResolveInfo manually from query?
I need it mock for unit tests
Please help me. I will direct very much thanks for you :)

**Comment by IvanGoncharov** [comment]
@marusapur It's technically possible to mock full `info` field however it will require to duplicate a lot of `execute` logic. To make it easier yo can use some **internal**(they are not a part of public API and subject to breaking change) functions exported from `execute.js`:
https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L683https://github.com/graphql/graphql-js/blob/ef288746c3c9d533ea66ddd153fd6fa09d5e718f/src/execution/execute.js#L683
https://github.com/graphql/graphql-js/blob/ef288746c3c9d533ea66ddd153fd6fa09d5e718f/src/execution/execute.js#L289

But the correct approach would be to extract logic from resolvers into a separate layer:
https://graphql.org/learn/thinking-in-graphs/#business-logic-layer
In general, GraphQL resolvers are intended to be thin layers that map GraphQL to your business logic code and as such, they are not intended to be unit testable.

**Comment by marusapur** [comment]
@IvanGoncharov Thank you but i already was try to use this methods. To use they for build fieldNodes from query is not easy because they are invokes too many times for one request(as i logging) and fieldNodes that coming as argument is already prepared(with locs, name, value etc). Also I was try logging methods that does execute buildResolveInfo method but they are also invokes too many times and it happens recursively. I can not find the method root method. May you help me please?

**Comment by IvanGoncharov** [comment]
@marusapur As I told before:
> It's technically possible to mock full info field however it will require to duplicate a lot of execute logic. 

So I strongly advise you to treat GraphQL as a black box and extract your business logic into separate functions and focus on unit testing them.

> fieldNodes that coming as argument is already prepared(with locs, name, value etc)

They are the output of `parse` function:
https://github.com/graphql/graphql-js/blob/49d86bbc810d1203aa3f7d93252e51f257d9460f/src/language/parser.js#L118

>  I can not find the method root method.

`execute` is a root method for query execution:
https://github.com/graphql/graphql-js/blob/49d86bbc810d1203aa3f7d93252e51f257d9460f/src/execution/execute.js#L137

**Comment by marusapur** [comment]
@IvanGoncharov Thanks a lot! It is exactly what i need!

**Comment by sbatezat** [comment]
I'm facing the same issue.

@IvanGoncharov I think you miss a point in the graphql recommendation (kind of a clean architecture).
Because business layer is not aware of the way it's used (rest, graphql, etc...) you should not write anything related to graphql inside. So basically, everything related to GraphQL, including GraphQLResolveInfo, should not be part of the business layer.

So now, let's think about a resolver that is extracting GraphQLResolveInfo to call the business layer with the right parameters (fields required), how do you manage the unit test of that? You can't put that logic in the business layer, because it's a GraphQL thing, and you have to unit test it to be sure it's working fine (the extraction of GraphQLResolveInfo to a "business readable model" is specific to the app).

**Comment by sbatezat** [comment]
@IvanGoncharov any chance to re-open this issue taking into account my comment?
