### ISSUE TITLE
Removal of experimental features in 15.0.0

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#2179]
We can remove some of the experimental features in `15.0.0`:
https://github.com/graphql/graphql-js/blob/2e1becb22e7ac37a9ed5b665136b92f9d1665c5e/src/language/parser.js#L95-L110

https://github.com/graphql/graphql-js/blob/2e1becb22e7ac37a9ed5b665136b92f9d1665c5e/src/utilities/TypeInfo.js#L57-L60

**Comment by IvanGoncharov** [comment]
@mjmahone @Neitsch Can you please check if you still using this features in FB codebase?

**Comment by mjmahone** [comment]
These features are used extensively by FB today.

The first, experimental fragment variables, are used a lot via the parser and AST. We don't currently use them over-the-wire at all, but there are hundreds (and growing) of usages. I'd be happy to move the parser/AST specifics to some form of plug-in model if we really don't want these experimental features to live in `graphql-js`, but removing fragment variable definitions will prevent FB from upgrading.

The second, TypeInfo field-definition-function-overriding, is still required due to FB's version of GraphQL still being split in some places between "legacy, before-OSS GraphQL" and "OSS spec compliant GraphQL". The primary thing this is used for is determining which field definition should be provided for a "fat interface", i.e. an interface that has access to all fields on all types that implement it. We'd love to kill all those non-spec-compliant queries, and we've been making progress on it, but we're definitely not free of them today.
