### ISSUE TITLE
RelayQueryWriter: Could not find a type name for record '1'

### ISSUE THREAD

**Issue by BerndWessels** [graphql/graphql-js#218]
Hello

I get `RelayQueryWriter: Could not find a type name for record '1'` when I do

    var appType = new GraphQLObjectType({
        name: 'App',
        description: 'The application configuration for the current user.',
        fields: () => ({
            id: {
              type: GraphQLID,
              description: 'The identifier'
            },
            email: {
              type: new GraphQLNonNull(GraphQLString),
              description: 'The user\'s email address'
            }
        })
    });

The `1` is the returned id value from the resolve.

Can anybody please explain to me what the magic around the `id` field is?

In some examples I see things like this `id: globalIdField('App'),`. But I do have my own ids from my database, what about those?

**Comment by leebyron** [comment]
You may have opened this issue on the wrong repository, you should open this on https://github.com/facebook/relay since it sounds like `RelayQueryWriter` is producing the error.

Your schema as written here looks completely valid. There is no magic to the `id` field from GraphQL's point of view, but Relay has specific add ons that may be related to your issue.
