### ISSUE TITLE
Syntax Error: Cannot parse the unexpected character "."

### ISSUE THREAD

**Issue by closertb** [graphql/graphql-js#2216]
# Questions regarding how to use GraphQL

I use graphql to query my github pages issues. but it failed. because when parse: **closertb.github.io**
![image](https://user-images.githubusercontent.com/22979584/66461098-daefcf80-eaaa-11e9-939b-372eb33814dd.png)
it throw error: 
![image](https://user-images.githubusercontent.com/22979584/66461141-f529ad80-eaaa-11e9-9d22-c8934ddda1c1.png)
# Reporting issues with GraphQL.js
i am surprise that this did not have the same question. am i wrong is use graphql?

# Feature requests

GraphQL.js is a reference implementation of the [GraphQL specification](https://github.com/graphql/graphql-spec). To discuss new features which are not GraphQL.js specific and fundamentally change the way GraphQL works, open an issue against the specification.

# Security bugs
can you tell me how to fix this?

**Comment by mike-marcacci** [comment]
Hi @closertb, this probably isn't the right place for this kind of question, since this isn't an issue with graphql-js at all. [StackOverflow](https://stackoverflow.com/questions/tagged/graphql) is a much more appropriate place for this.

That said, the error explains the problem encountered by the parser: the value in `name: closertb.github.io` needs to be enclosed in `"`. The same will be true for `owner: closertb`, which will also cause an error.

**Comment by IvanGoncharov** [comment]
@mike-marcacci Thanks for the excellent answer 👏 
It helps a lot 👍

**Comment by closertb** [comment]
> Hi @closertb, this probably isn't the right place for this kind of question, since this isn't an issue with graphql-js at all. [StackOverflow](https://stackoverflow.com/questions/tagged/graphql) is a much more appropriate place for this.
> 
> That said, the error explains the problem encountered by the parser: the value in `name: closertb.github.io` needs to be enclosed in `"`. The same will be true for `owner: closertb`, which will also cause an error.

thanks. i do not aware of that
