### ISSUE TITLE
Unable to make cross links between types

### ISSUE THREAD

**Issue by vslinko** [graphql/graphql-js#23]
Vectors in graph could reference to each other in any direction.
So I should be able to use GraphQL type before it's implementation.
I don't found a possibility to do this right now. Am I right?

**Comment by vslinko** [comment]
Also GraphQL type could reference to itself.

**Comment by leebyron** [comment]
GraphQL types can refer to themselves by implementing `fields` as a function rather than an object. In fact, supplying an object is a shorthand for a function that returns that object:

```
var RecursiveType = new GraphQLObjectType({
  name: 'Recursive',
  fields: {
    recurse: { type: RecursiveType }
  }
});
```

Will not work because you reference `RecursiveType` before it's defined. Instead, use a function for fields.

```
new GraphQLObjectType({
  name: 'Recursive',
  fields: function () {
    return {
      recurse: { type: Recursive }
    }
  }
});
```

Or if you're using ES6 arrow functions


```
new GraphQLObjectType({
  name: 'Recursive',
  fields: () => ({
    recurse: { type: Recursive }
  })
});
```

**Comment by vslinko** [comment]
@leebyron Thank you very much for quick reply!

**Comment by maletor** [comment]
Is this possible across multiple files? The arrow function creates a closure around what's around it but I don't think this would work if you wanted all of your types in unique files, right?

**Comment by kiotoze** [comment]
@leebyron Very helpfull, thanks!
That happened to me when I include same GraphQLObjectType in different files. But I have also Enum dependent in different files
Do you know how to make same trick with GraphQLEnumType?

**Comment by bentron2000** [comment]
@leebyron 

Thanks for the tips here. 

What if I'm declaring a `GraphQLUnionType` instead of `GraphQLObjectType`?

I have a NestedType with a 'parent' attribute that is defined as a UnionParentType.

```
const UnionParentType = GraphQLUnionType({
  name: 'ParentType',
  types: [RootType, NestedType],
  resolveType: (parent) => {
    if (parent instanceof Root) {
      return RootType;
    }
    return NestedType;
  }
});
```

When I run this - It doesn't work. 
I get an error `Error: ParentType may only contain Object types, it cannot contain: undefined.
`

Is it possible to work recursively like this with union types?

**Comment by tuxsudo** [comment]
> Is it possible to work recursively like this with union types?

The `types` property of a `GraphQLUnionType` [can also be thunk](http://graphql.org/graphql-js/type/#graphqluniontype), so the previous error might be fixed with:

```
const UnionParentType = GraphQLUnionType({
  name: 'ParentType',
  types: () => [RootType, NestedType], // <--- this changed
  resolveType: (parent) => {
    if (parent instanceof Root) {
      return RootType;
    }
    return NestedType;
  }
});
```

I was also getting an error like: 

> *Type* may only contain Object types, it cannot contain: undefined

It was fixed by changing `types` from an array to a function that returns an array.
