### ISSUE TITLE
Dynamic defaultValue

### ISSUE THREAD

**Issue by xpepermint** [graphql/graphql-js#240]
I would like to pass a function to the `defaultValue`. Currently only a `value` (`string`) is expected.

Example:
```js
createdAt: {
  type: DateTimeType,
  defaultValue: () => new Date()
}
```

**Comment by leebyron** [comment]
defaultValue is specifically intended to be static so that introspection can safely serialize the defaultValue and clients could use introspection to determine if they need to provide.

This example falls into the realm of problems of "time is hard". Time is relative, and a client provided timestamp and a server provided timestamp and a database known timestamp may all mean different things. There is also time drift to consider. Making the default value be "now" may result in drift between the moment when the value is resolved and the moment when the value is used within a resolver.

Perhaps the default value should actually be "null" and the resolve code should be responsible for handling it's interpretation of "now"?

**Comment by xpepermint** [comment]
Hum... I see your point. I guess you are right about the `null` value - my current solution. I think we can close it ...
