### ISSUE TITLE
Error: Unknown type "Query"

### ISSUE THREAD

**Issue by FranOnRails** [graphql/graphql-js#2506]
I didn't find anything about this error so I decided to post here. 
throw new Error(errors.map(function (error) {
    ^
Error: Unknown type "Query".
src: https://github.com/FranOnRails/Slack-Clone-Server/tree/develop

**Comment by IvanGoncharov** [comment]
@FranOnRails You use duplicate version of `graphql` package:
https://github.com/FranOnRails/Slack-Clone-Server/blob/258bebaa0f5d06bc67a6979bf478705e6c9e7798/yarn.lock#L2506-L2516

Please use only one, for details see: https://github.com/graphql/graphql-js/issues/2503

**Comment by yaacovCR** [comment]
The issue of n^2 queries won't be solved by batching and should be fixed in makeRemoteExecutableSchema.

In the meantime, in the alpha versions, you should be able to do use the new wrapSchema function instead of makeRemoteExecutableSchema, which hopefully should not have this problem, as follows:

```
const remoteSchema = wrapSchema({
  schema: schemaFromIntrospection,
  link: <your_link>,
  transforms: <your transforms>
});
```
The intended benefit of wrapSchema is that you can create a remote schema and apply transforms with only one round of delegation. A side benefit, hopefully, is that it does not have the n^2 problem.

I would refactor makeRemoteExecutableSchema to use wrapSchema under the hood. But, I am having trouble doing that in a backwards compatible way, as makeRemoteExecutableSchema takes these custom resolver arguments.

Getting closer, though.
