### ISSUE TITLE
Jest unit test case will execute before executing actuall function so getting error in expect part

### ISSUE THREAD

**Issue by anjneeksharma** [graphql/graphql-js#2598]
AddingFeedback will not execute fully by the time all the test cases will execute 

it('addFeedback should create a feedback', done => {
    request
      .post('/graphql')
      .send({
        query: query,
        operationName: 'AddingFeedback',
        variables: {
          input: mock
        }
      })
      .expect(res => {
        expect(res.body).not.toHaveProperty('errors');
        expect(res.body).toHaveProperty('data');
        expect(res.body.data).toHaveProperty('addFeedback');
        expect(res.body.data.addFeedback).toHaveProperty('_id', mock._id);
        expect(res.body.data.addFeedback).toHaveProperty('description', mock.description);
        expect(res.body.data.addFeedback).toHaveProperty('ticketID', mock.ticketID);
        expect(res.body.data.addFeedback).toHaveProperty('experience', mock.experience);
      })
      .end((err, res) => {
        done(err);
      });
  });

**Comment by danielrearden** [comment]
Without seeing all the relevant code, it's hard to know for sure but this is most likely an issue with your resolver. Typically, it means you have an "orphaned" Promise that wasn't returned inside the resolver or otherwise correctly chained to another Promise. See [this Stack Overflow post](https://stackoverflow.com/questions/56319137/why-does-a-graphql-query-return-null) for a more detailed explanation.

If you have additional questions, Stack Overflow is a great resource that may already have the answers you're looking for. Check out [these links](https://graphql.org/community/) for additional community resources as well.
