### ISSUE TITLE
"Must provide operation name if query contains multiple operations"

### ISSUE THREAD

**Issue by ivawzh** [graphql/graphql-js#260]
Hi. I am trying to put a mutation and a query inside one request. I have found an example from [express-graphql test](https://github.com/graphql/express-graphql/blob/master/src%2F__tests__%2Fhttp-test.js#L299-L300) . However, when I implement this in my code, I got error: "Must provide operation name if query contains multiple operations"

My POST request's body:
```
mutation login {
  createSession(email:"test@123.com", password: "foobar"){
    session
  }
}

query me {
  deserializeUser{
    id,
    email,
    name
  }
}
```
And I have set up schema `RootQuery` and `RootMutation` with fields - `createSession` and `deserializeUser` already. The session is passed to `deserializeUser` via `req`. 

Please give me some clues. Thanks in advance.

**Comment by eyston** [comment]
Operation name is the fifth argument to the `graphql` function.  Only one operation will execute at a time but its possible (like your example) to have multiple operations per document.  So you could supply this query to `graphql` and specify 'me' or 'login' as the operation name.

**Comment by ivawzh** [comment]
What I want is a bash with a mix of mutation and query within one http request. I still can't find any document that shows me how to do this properly. I'm using koa-graphql (or 'graphqlHttp'). Would you please give some examples or a link to documentation please

**Comment by eyston** [comment]
Just guessing but your use case can probably be accomplished by having the mutation include the data it mutates as a fields:

```
mutation login {
  createSession(email: "test@123.com", password: "foobar") {
    user {
      id
      email
      name
    }
  }
}
```

If you want to perform a `mutation` and `query` from the same document they'd be two separate executions each with their own response.

**Comment by ivawzh** [comment]
I would still want to discuss further about 'perform a mutation and query from the same document'. Do we have documentation for this? 

When you say "they'd be two separate executions each with their own response", do you mean this one HTTP request will generate two JSON responses to the client asynchronously?  

And in [express-graphql test](https://github.com/graphql/express-graphql/blob/master/src%2F__tests__%2Fhttp-test.js#L299-L300):
* why do we set `operationName` to query's name, but not mutation's?
* how does the mechanism of "they'd be two separate executions each with their own response" affect the output of highlighted document? From the test, the output looks similar to usual response: 
```
        expect(JSON.parse(response.text)).to.deep.equal({
          data: {
            test: 'Hello World'
          }
        });
```

Thanks =]

**Comment by eyston** [comment]
I'm trying to separate HTTP from graphql when I say 'executions'.  Since this is the `graphql-js` issue list I want to avoid talking about any specific HTTP library :).

So by `executions` I mean the calling of the `graphql` function.  e.g. `graphql(schema, query, root)`, etc.

If your query has multiple operations and you want to evaluate all of them you'd have to call the `graphql` function multiple times -- once per operation name.

- `graphql(schema, query, root, vars, 'login')`
- `graphql(schema, query, root, vars, 'me')`

You would now have two responses.

The test on `express-graphql` is an example of having multiple operations -- TestMutation and TestQuery -- and specifying which one you want to execute via operation name.  In the example the operation name is 'TestQuery' so it is the one that executes.  You could remove `TestMutation` from that query entirely and it would be the same result.

I imagine most HTTP libraries map a request to a single graphql execution so in order to execute both operations it would require multiple requests.  This is not a requirement though and there is nothing preventing an HTTP library from accepting an array of queries per request -- graphql doesn't care.

**Comment by ivawzh** [comment]
Thanks for the awesome explanation Huey!  I realise myself am going quite off-topic here. I will probably shoot more questions in `express-graphql` instead.

**Comment by tahnik** [comment]
@ivawzh did you find a solution for this?
