### ISSUE TITLE
Type introspection by Scalar Name

### ISSUE THREAD

**Issue by jontonsoup** [graphql/graphql-js#262]
I posted this in the graphql repo, but it seems this issue actually should be posted here.  
https://github.com/facebook/graphql/issues/126

Say I define a Custom Scalar type: 

```
export var GraphQLNewFancyType = new GraphQLScalarType({
  name: 'NewFancyType',
   ...
});

```

And use that type as an field value in an object: 

```
...
  fields: {
    new_fancy_type: {
      type: GraphQLNewFancyType,
      description: 'A great new type!'
    },
...
```

Is there where to do an introspection query to return all the queries that use this new scalar type without listing everything recursively and doing the parsing manually?

Thanks!
Jon

**Comment by leebyron** [comment]
I'm not sure I understand your question. Could you clarify what you mean by where to do an introspection query?

**Comment by jontonsoup** [comment]
@leebyron whoops typo -- I am asking for (I think) a new type of introspection. I want to ask graphql what queries have a specific type as a field.

**Comment by leebyron** [comment]
I'm still not completely sure I understand your question, but let me do my best:

If you're talking about queries: since a GraphQL server can fulfill numerous and varied queries, it might not be possible to know what queries access a field of a particular type. If you have a client codebase where you are defining your queries ahead of time, it seems reasonable that you could produce some code that operates over those queries and can determine which queries access fields of any type. We actually have a service that works something like this at Facebook, its output is usually some automatically generated code.

If you're talking about asking GraphQL what types in its schema have fields of a particular type, the best way to do this is to write a query against introspection which access all fields and then filter this down once the request returns to determine which fields on which types return a particular type. For example:

```
{
  __schema { 
    types { 
      name, 
      fields { 
        name, 
        type { 
          name 
        }
      }
    }
  }
}
```

Then

```js
for (let type of __schema.types) {
  for (let field of type.fields) {
    if (field.type.name === 'NewFancyType') {
      console.log(`${type.name}.${field.name}: NewFancyType`);
    }
  }
}
```

Hopefully this answers your question

**Comment by jontonsoup** [comment]
I was speaking about the latter-- thanks!

Best,
Jon
