### ISSUE TITLE
Fields with same arguments from different variables can't be merged

### ISSUE THREAD

**Issue by fson** [graphql/graphql-js#263]
graphql-js merges overlapping fields when they have the same arguments, but not if the values come from different variables, even if the variables have the same value.

For example, given variables: `{ "orderBy": "NAME_ASC", "orderBy2": "NAME_ASC" }` this merges without problems:
```
query ($orderBy: _GroupOrdering) {
  viewer {
    allGroups(orderBy: $orderBy) { count }
    allGroups(orderBy: $orderBy) { count }
  }
}
```
But this fails with `Fields "allGroups" conflict because they have differing arguments.`:
```
query ($orderBy: _GroupOrdering, $orderBy2: _GroupOrdering) {
  viewer {
    allGroups(orderBy: $orderBy) { count }
    allGroups(orderBy: $orderBy2) { count }
  }
}
```
This is an issue when using Relay because it can produce queries like this in some cases.

The relevant line of code seems to be here: https://github.com/graphql/graphql-js/blob/a6bcc75d3c19ce31847cd77279a41fbc6ac032d2/src/validation/rules/OverlappingFieldsCanBeMerged.js#L209 It only compares the names of variables. Should we also take the variable values in account when validating if the fields can be merged?

**Comment by dschafer** [comment]
We want the validator stage to be able to run independently of the values of variables; this allows us (for example) to validate and persist the query text, then send up an identifier for that persisted query along with the variable values and skip validation (because it was already validated).

> This is an issue when using Relay because it can produce queries like this in some cases.

Sounds like this is a bug in Relay to me? @josephsavona @yungsters ?

**Comment by leebyron** [comment]
As @dschafer pointed out, we want to ensure validation is done without the variable values. This lets us ensure a query is valid statically before runtime. For example, to run validation on queries within a codebase to ensure they are valid before they are even run.

I opened an issue on Relay since it certainly seems like Relay should not produce invalid queries like this.
