### ISSUE TITLE
v15.1.0 Unable to resolve defineToJSON

### ISSUE THREAD

**Issue by exneval** [graphql/graphql-js#2646]
GraphQL version: 15.1.0

Unable to resolve jsutils/defineToJSON at language/ast.js

revert back to 15.0.0 has no problem

**Comment by danielrearden** [comment]
Thanks for the bug report.

This file was recently renamed. There are no more references to `defineToJSON` in the code, so it's not clear from just the error above what the problem is. Please verify that you only have one version of `graphql` in your dependencies. Delete `node_modules` and run `npm install` (or `yarn install`) again. Then run `npm ls graphql` (or `yarn list graphql`) to verify that only one version of graphql is installed.

**Comment by exneval** [comment]
Thanks for responding @danielrearden 
I took your advice and this is what I've encountered

This is the error:
![1](https://user-images.githubusercontent.com/3431785/84480883-7206ca00-acbf-11ea-8fd4-806b00857a06.png)

and this is the list of the graphql
![2](https://user-images.githubusercontent.com/3431785/84480933-84810380-acbf-11ea-930b-7ee3cf64ec43.png)

Any advice for it?
Thanks in advance

**Comment by krakzk** [comment]
Facing the same issue in 0.62.2.
 @exneval Any solution to resolve this?
