### ISSUE TITLE
Expose getArgumentValues from root

### ISSUE THREAD

**Issue by thomas-jeepe** [graphql/graphql-js#2719]
`getArgumentValues` is marked as internal and only exposed when you import from `graphql/execution/values`.

If you could expose it from the root `index.js` it would make importing it far easier in contexts without imports to relative files (a cdn for my case.)

The function is already used in production ready code in joinmonster and is necessary to get arguments from resolve info in field handlers. I don't see a good reason not to expose it.

**Comment by hayes** [comment]
I've seen several places that either use getArgumentValues, or suggest using it.  Is there a reason it is currently not exposed from the index?  Happy to make a PR if it's just an oversight

**Comment by benjie** [comment]
@IvanGoncharov do you know if there is a good reason for this to be internal only?

From what I can tell it receives a fair bit of use from the community, and it [seems a bit too complex](https://github.com/graphql/graphql-js/blob/47bd8c8897c72d3efc17ecb1599a95cee6bac5e8/src/execution/values.ts#L150-L234) to just copy and paste into a project.

We're currently facing issues with there being no TypeScript declaration for this export, which is preventing us adopting GraphQL v16:

```
src/index.ts:20:10 - error TS2305: Module '"graphql"' has no exported member 'getArgumentValues'.

20 import { getArgumentValues } from "graphql/execution/values";
            ~~~~~~~~~~~~~~~~~


Found 1 error.
```

Surfacing this as a top level export would be appreciated :+1:

**Comment by sachaw** [comment]
Is there any plans to work around this, It's currently blocking upgrading a number of large projects for me, and is starting to become a problem.
Thanks.

**Comment by IvanGoncharov** [comment]
@benjie @sachaw TS error that you experience should be fixed by https://github.com/graphql/graphql-js/commit/c2435fd1b8b22e034ad1b266bf092ace0e06d015#diff-8fa9d179bb9179cc71534c34c492beb7bd8742db13f0fa1b6b269b5dc726a7f3
and released as `graphql@16.2.0`.
Can you please test updating directly to `16.2.0`?

As for exporting `getArgumentValues` it's internal function and was never intended to be part of public API.
However, since there are no alternatives to achieve the same functionality `getArgumentValues` defacto became part of public API.
So I will expose it, however, long-term solution would be to design it as a separate stage of the execution pipeline (similar to `validate` for example) so please expect breaking change in the next major release.

**Comment by saihaj** [comment]
@IvanGoncharov as discussed in WG today incorrect function was exposed.

**Comment by hiepxanh** [comment]
hope this will be resolve soon, I really expect this issue will be resolve since I'm using postgraphile and stuck with graphql version 15 for a long time :D

**Comment by paulbijancoch** [comment]
any news on this?
