### ISSUE TITLE
Render all items of query

### ISSUE THREAD

**Issue by RitikDua** [graphql/graphql-js#2746]
I doesn't find any syntax for rendering all query  items at once. 
It would be much easier if we can render all items of query at once like this:
```
query{
    User{
          name
          email
          info
          age
          followers
   }
}
```
to 
```
query{
        User{
             *
     }
}
```

**Comment by danielrearden** [comment]
It's impossible to know what "all" the possible fields for a selection set would be considering that:
* Each field may take one or more arguments. Given a field definition like `followers(first: Int)`, the value of `first` could be any value between -2<sup>31</sup> and 2<sup>31</sup>. It's up to the client to explicitly provide the right value depending on the meaning of the argument (as determined by the service) and the needs of the client.
* A selection set may have no maximum depth due to potentially recursive type definitions. For example, if the type of the `followers` field is `[User]`, then the client would need to determine the appropriate depth to which request followers:

```graphql
query {
  user {
    id
    followers {
      id
      followers {
        id
        # etc.
      }
    }
  }
}
```

Additionally, one of the guiding principles behind GraphQL is returning predictable results. Even if it were possible to implement a syntax for getting "all possible fields", it would still be inadvisable because you'd lose the predictability and type-safety that you otherwise get. The structure of the returned data would no longer be dictated by the client; it could change at any time depending on changes to the schema.

**Comment by RitikDua** [comment]
> It's impossible to know what "all" the possible fields for a selection set would be considering that:
> 
>     * Each field may take one or more arguments. Given a field definition like `followers(first: Int)`, the value of `first` could be any value between -231 and 231. It's up to the client to explicitly provide the right value depending on the meaning of the argument (as determined by the service) and the needs of the client.
> 
>     * A selection set may have no maximum depth due to potentially recursive type definitions. For example, if the type of the `followers` field is `[User]`, then the client would need to determine the appropriate depth to which request followers:
> 
> 
> ```graphql
> query {
>   user {
>     id
>     followers {
>       id
>       followers {
>         id
>         # etc.
>       }
>     }
>   }
> }
> ```
> 
> Additionally, one of the guiding principles behind GraphQL is returning predictable results. Even if it were possible to implement a syntax for getting "all possible fields", it would still be inadvisable because you'd lose the predictability and type-safety that you otherwise get. The structure of the returned data would no longer be dictated by the client; it could change at any time depending on changes to the schema.

Thanks for explaining this to me.
