### ISSUE TITLE
Export defaultResolveFn for efficient same-table queries?

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphql-js#275]
Let's say I've got a table with an `isAJerk` field. Unless the person making the query is an admin, I don't want them to see the value of this field, so I do something like this (I call graphQL with an `authToken` in the `rootValue`):

```
resolve(source, args, info) {
        return info.rootValue.authToken.isAdmin ? defaultResolveFn.apply(this, arguments) : null;
      }
```

Is this the right way to do it? It seems right since I don't have to make a second DB query. If so, does it make sense to export the `defaultResolveFn`? This would mean no dev would have to make their own copy of the function, which makes it a little cleaner & futureproof.

**Comment by leebyron** [comment]
I think this would probably be overkill. Presumably you understand your data domain well in order to set up the GraphQL mappings. `defaultResolveFn` is there because GraphQL does not understand your data domain and this function is GraphQL's attempt at doing something reasonable.

If you're already writing something like this to do privacy checking (which is totally reasonable by the way), then the assumption is that you could rewrite this to be more clear, like:

```js
resolve(source, args, info) {
  return info.rootValue.authToken.isAdmin ? source.myField : null;
}
```

In general, I try to only export functions that regularly provide value externally and are part of the external contract. However this function is so small and simple that it doesn't bother me at all if you want to copy its implementation and mess with it to do your own thing like adding this kind of admin check.
