### ISSUE TITLE
Correct way to handle unstructured property values

### ISSUE THREAD

**Issue by orktes** [graphql/graphql-js#32]
Hi,

First of all, I´d like to thank you for the awesome job you have done with the spec and this reference implementation. It took only couple of hours to build a GraphQL "proxy" server by generating GraphQL schema from a preexisting JSON schema definition we had for our REST API and I'm already experiencing the benefits.

The only question I have is this; We have some abstract field types in our api. For example some responses may contain user supplied JSON metadata. This means I'm unable to define the actual fields and types for the data. Currently I'm using an ugly way to handle these fields by creating a scalar type and using that for the metadata fields.

```js
var GraphQLAnything = new GraphQLScalarType({
  name: 'Anything',
  coerce: function (value) {
    return value;
  },
  coerceLiteral: function (ast) {
    return ast.value;
  }
});
```

This works as desired (I'm able to receive the data in correct form) but defining something like this as a scalar feels wrong in so many levels. Especially as the spec says that "Scalars cannot have fields.". Is there a correct way to handle these type of values?

Thanks!

**Comment by leebyron** [comment]
Can you explain what you mean by abstract types in this context? In GraphQL "abstract types" has a concrete definition of Union or Interface types.

If I understand correctly (and please correct me if I don't), the data in question is just unstructured and unpredictable, and so you can't write sane queries against it. Is the fact that you represent the data as JSON is a coincidence, and it could have just as easily been binary data, or anything else?

We have a few rare places in Facebook where data operates this way, and we've exposed it through GraphQL as a String, where we actually JSON encode the data on the way out, rather than embedding it directly. This ensures clients don't accidentally index into the data thinking that it is safe, instead requiring an explicit JSON decode to access the unsafe user provided data.

Otherwise, I don't think what you've done here is all that bad, though I may suggest changing the type from "Anything" to "JSON" or something along that line.

Maybe you could offer how you expected or hoped this sort of thing would work?

**Comment by orktes** [comment]
Sorry using "abstract" in this context was a little bit vague, but you understood me correctly :) The data in our case is always JSON (even distinction between object and array is known) but it is otherwise unstructured.

I went with JSON encoding + GraphQLString at first also but that would have resulted in additional refactoring on the client side views so decided to look for something that keeps the olds structure of our data.

GraphQLJSONObject is actual naming I use but decided to use GraphQLAnything for the snippet to broaden the question area so discussion here might help people with more varied needs.  

I'm otherwise fine with doing it like this, but wanted to ask if mixing non-scalar values with GraphQLScalarType would result in possible side effect now or in the future?

**Comment by leebyron** [comment]
I don't think there are any side-effects to worry about. GraphQL will treat this value as a "scalar" as in a "leaf-value" - it just so happens that the output format is just raw.

I would suggest avoiding using naming like "Anything" because it sounds like something to be used. Even "JSONObject" is maybe too reasonable :). I'd suggest something like "DangerousUserProvidedUnstructuredJSON" :P - maybe that's a little extreme, but any way to clearly explain the difference between your well-typed data and ¯\_(ツ)_/¯ data is going to be useful.

**Comment by leebyron** [comment]
One last note: as currently written your `coerceLiteral` method will only work on simple scalar inputs. If you only need GraphQL to describe the output of these unstructured blobs, then maybe even just put a `throw Error()` in there... otherwise you may need to focus a little more attention on the array/object literal input cases.

**Comment by orktes** [comment]
Thanks for the quick answer!

"DangerousUserProvidedUnstructuredJSON" inspired me to find a way to convert the old unstructured data into something structured :D

Closing....

**Comment by leebyron** [comment]
Nice! Best of luck

**Comment by chrisabrams** [comment]
@orktes could you provide an example of how you are trying to use this with a query? I tried doing [something similar](https://github.com/graphql/graphql-js/issues/357) but cannot seem to figure out how to format the query.

**Comment by AlirezaHaghshenas** [comment]
@leebyron 
Now in 2021, has anything changed about this discussion?
Is there now some other ways to expose unstructured data? Or a scalar string field that contains json representation is still a best practice?

**Comment by tamimdocxster** [comment]
> @leebyron Now in 2021, has anything changed about this discussion? Is there now some other ways to expose unstructured data? Or a scalar string field that contains json representation is still a best practice?

You can use Map GQLgen type to represent Objects.
