### ISSUE TITLE
Query validation failure shouldn't block execution

### ISSUE THREAD

**Issue by helfer** [graphql/graphql-js#324]
[Section 5 of the GraphQL spec](https://facebook.github.io/graphql/#sec-Validation) says the following:

> Servers (as described in the Execution section of this spec) attempt to satisfy as much as the request as possible and continue to execute in the presence of type system errors rather than cease execution completely.

Despite what the spec says, the `graphql(schema, query)` function - which I believe fits the spec definition of a 'server' - currently rejects queries that do not pass validation. For example, queries containing any of the following will be rejected without execution:

- Variables that are defined, but never used
- Fragment spreads of a type that cannot match the type it is used it.
- Selection sets with one or more fields that are not defined on this type

I think the first two cases could easily be ignored, and in the third case, the field could either not be included in the result or set to null. In all of these cases, a validation or execution error should be added to the response.

I realize that fixing this is most likely not as simple as removing the validation step, and that's exactly why I thought it best to bring it up here:

Is the non-compliance with the spec intentional? If it is not, would major changes to the execution stage be necessary to safely resolve queries without prior validation?

**Comment by freiksenet** [comment]
I think from those three, only first one is the one I'd feel safe ignoring, all other errors are valuable and most probably indicate a broken query.

**Comment by helfer** [comment]
I picked these three examples rather arbitrarily. What I would like to have is a discussion about whether validation errors should prevent query execution in general, not a discussion about these specific examples.
The way I understand it, validation is intended to surface possible mistakes during development. During execution, the server should try to satisfy as much of a request as it can. That is essentially what the spec says. As long as the query is syntactically correct and the interpretation is not ambiguous, I don't see a reason for failing completely rather than fulfilling as much of the request as possible and producing a warning.

If people think that stopping execution if validation fails is a useful feature, maybe it could be supported by adding a 'strict' keyword to a query if the client wants that.

**Comment by leebyron** [comment]
This behavior of not executing invalid queries is spec compliant. If there is ambiguity in the spec we should clear that up. There are two kinds of errors you can encounter:

**1) Pre-execution error**

A syntax error or validation error is detectable before an execution begins. If there are any pre-execution errors, execution should not take place.

**2) Field-resolution execution error**

During execution, an error occurred when resolving a field. Those errors get cataloged in an "errors" array, the field is nulled out and execution continues. This is what is discussed in the spec as "attempt to satisfy as much as the request as possible".

**Comment by leebyron** [comment]
You can execute a query that does not pass validation, or you can execute a query without even performing validation. Every query should have a well defined execution output. Validation just ensures that the query does not contain ambiguity errors that could lead to misinterpretation.

There are reasons why you might not perform validation on a server and one case you brought up: if you're performing validation in your development environment to ensure all queries used in a production environment are valid, but without actually performing validation in production. We actually do this for most of our queries at Facebook. However we definitely still ensure that only valid queries make it to a production environment, and we do not allow execution of invalid queries in our development environment.

The philosophy for not executing invalid queries is this: field errors happen because something happened that is the fault of the *server* at *runtime* that we couldn't have anticipated. It's not fair to fail a whole query if it can be avoided to limit the fallout of these kinds of errors. However invalid queries represent a knowable error that is the fault of the *client* (e.g. whoever is writing the queries). Failing these fast ensure responses that cannot be misinterpreted and presents confidence that if your query is running then it is well formed. If there is an error, then you will know about it. It would be very easy to simply ignore validation errors if we just executed them anyway, validation issues would simply become error spew.

**Comment by leebyron** [comment]
I've got a proposal up at https://github.com/facebook/graphql/pull/158 to help clarify the spec with regards to this.

**Comment by helfer** [comment]
Thanks for clarifying, it does sound very different now. In particular, it no longer says that the server should "attempt to satisfy as much of the result as possible in the face of type system errors".
I'm not 100% sure if it's necessary to be as strict as the spec describes now, but at least there's no room for ambiguity.
I'll open another issue if I think I have a good use case to justify being more lenient.
