### ISSUE TITLE
Introduce monorepo architecture with scoped packages

### ISSUE THREAD

**Issue by yaacovCR** [graphql/graphql-js#3321]
Consider dividing this package into `@graphql/schema`, `@graphql/execution` in a true multipackage monorepo design instead of the loosely divided current "module" setup.

This would allow much easier forking of the executor for customization, without running into the "multiple versions of graphql issue."

A current alternative that points the way is [`graphql-executor`](https://github.com/yaacovCR/graphql-executor/).

**Comment by IvanGoncharov** [comment]
> i am not sure why build step with Babel is easier than monorepo structure.

A couple of reasons, from top of my head:
1. There is no standardization on module loading in the JS ecosystem so I don't want to restrict non-node use cases (e.g. Deno, native ESM from browsers, etc.). Provide bundled version of `graphql` for those platforms provide them with worst DX.
2. It complicates tooling, we need to use staff like `lerna` instead of using `npm` directly
3. `jsutils` is an internal package with private API and no `index.ts` (by design) but we would need to publish it as a package anyway.
4. Where stuff like `version.ts` will leave? 
5. Most important: If end-users need to add 8 separate packages to `peerDependencies` it provides bad DX and multiple confusion that we currently have over "multiple versions of graphql issue." by a factor of 8.
6. `instanceOf` check helps us to prevent bugs due to passing objects between incompatible `graphql` versions. But for modules like `language` we can't use `instanceOf` so that means can't prevent scenarios where one version of `@graphql/language` is used to produce AST but an incompatible one is used to print AST.

I like your approach with `graphql-executor` and this is something we can easily do in a few build steps, I can even publish it to a separate branch on every commit similar to `npm` and `deno` branch. It means `graphql-executor` can be a list of patches on top of this branch, hopefully, we can keep this list small and temporary.

> the use case is as mentioned above, much easier approach to forking executor.

Can you please list what problems it solves?
Because the only one I'm aware of is to have different import paths.
Do you have any other problems in mind solved by monorepo?

**Comment by saihaj** [comment]
so we make a new package `graphql-core` which will have all the modules as dependencies `@graphql/language`, `@graphql/executor` and etc. When we are releasing we bundle this package up into `graphql` and we publish it as we normally do. Users who want to customize specific packages they can use `graphql-core` then they have to manage peer deps for all the packages they decide to use and for others they can continue to use `graphql` normally. With bundling we can also generate packages specific for `deno` and for web we can even have a slimmed down version like [`graphql-web-lite`](https://github.com/kitten/graphql-web-lite)

**Comment by IvanGoncharov** [comment]
I actually likes idea of `graphql-executor` so I think we just need to make it easier to maintain that's why I suggested babel transform and publishing branch.
But maybe it worth to return to the previous idea of class with unstable API but publish it as `@graphql/execution` (with imports from `graphql`).
@yaacovCR It solves biggest problem of "unstable class" API we discussed. What do you think?

**Comment by yaacovCR** [comment]
On much later reflection, @IvanGoncharov , I think your raised a number of important blockers for the above work, especially the internal versioning and intercompatibility issue, the "internal" tools.

I think it would be helpful in the long-term still to move in that direction, but it would certainly require work addressing your above points. I might be able to tackle work on some of those blockers, but not in the short or probably even medium-term.

The overall goal is still excellent imo, i.e. making it easy to plug and play aspects of the graphql pipeline. How to get there is not so clear!
