### ISSUE TITLE
Graphql v16 (or higher) does not work with Relay 

### ISSUE THREAD

**Issue by BiancaArtola** [graphql/graphql-js#3429]
# Reporting issues with GraphQL.js

I am working on a React project using Relay and Graphql. This is my `package json`:
```

 "dependencies": {
    "axios": "^0.21.2",
    "mobx": "^6.3.5",
    "mobx-react-lite": "^3.2.1",
    "oidc-client": "^1.11.5",
    "react": "^17.0.2",
    "react-device-detect": "^2.0.0",
    "react-router-dom": "^5.3.0",
    "styled-components": "^5.3.3"
  },
  "devDependencies": {
    "@types/node": "^16.3.2",
    "@types/react": "^17.0.10",
    "@types/react-dom": "^17.0.7",
    "@types/react-relay": "^11.0.2",
    "@types/react-router-dom": "^5.1.7",
    "@types/relay-runtime": "^12.0.0",
    "@types/styled-components": "^5.1.10",
    "babel-plugin-relay": "^12.0.0",
    "env-cmd": "^10.1.0",
    "graphql": "^16.1.0",
    "prettier": "2.4.1",
    "react-app-rewired": "^2.1.8",
    "react-scripts": "^4.0.3",
    "relay-compiler": "^12.0.0",
    "relay-config": "^12.0.0",
    "react-dom": "^17.0.2",
    "react-relay": "^12.0.0",
    "relay-runtime": "^12.0.0",
    "typescript": "^4.3.2",
    "relay-compiler-language-typescript": "^15.0.0"
  },

```

After the Graphql update from version 15.x to 16.x Relay does not work anymore with Graphql. When I run `yarn run relay`, the following error appears:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/21174759/146256401-40efbd73-eabc-4982-9c51-78e64cfa6ae7.png">

**Comment by saihaj** [comment]
Hey @BiancaArtola Supporting `v16` at the moment with `relay` and `relay-compiler-language-typescript` is little bit challenging because:

1. Back when we were migrating `graphql-js` to Typescript #2828 we decided to drop support for flow #2832. And `relay` < `v12` is uses Flow. So the challenge to upgrade there is we need to get Flow types in order to support `graphql@v16`.
2. Which brings us to error you are getting. With `relay-compiler-language-typescript` that directly depends on `relay-compiler` and since it  doesn't support `v16` that is why you get that TS error. See https://github.com/relay-tools/relay-compiler-language-typescript/issues/507

With upcoming [`relay@13`](https://github.com/facebook/relay/releases/tag/v13.0.0-rc.0) release the compiler is written in rust and to my knowledge it doesn't depend on `graphql-js` and based on these release notes it support TS code generation out of the box https://github.com/facebook/relay/pull/3182

So far the only major project I have seen is impacted with Flow types not being available with `graphql-js` is `relay`. FWIW I think just waiting for stable `relay@13` is  better idea.

**Comment by BiancaArtola** [comment]
Thanks for the response @saihaj. I will wait for `relay@13`, thanks
