### ISSUE TITLE
`getDescription` is not exported

### ISSUE THREAD

**Issue by Lonli-Lokli** [graphql/graphql-js#3490]
Same as reported here - https://github.com/graphql/graphql-js/pull/1165

Starting with v16 this method has been removed from public so we are facing errors with nestjs & gql

**Comment by Jakub41** [comment]
Hello, I'm facing the same issue and is not possible to get it back as was done in the past? 
Would be good then...

**Comment by is2ei** [comment]
I'm not sure the reason why it's deprecated but the method is removed completely because it's deprecated.
Ref: https://github.com/graphql/graphql-js/commit/ec2352a3801e9c9cf462447f79f9d7235f84b757

**Comment by IvanGoncharov** [comment]
`getDescription` method was part of experimental SDL support and was required to handle "description as comment syntax".
Many years ago we finalized the SDL design that uses a different syntax for description without the need for `getDescription` (new syntax handled in AST).
We deprecated this function since v14 (~4years ago) and finally remove it.
I understand the frustration but we need to drop support for "experimental" stuff that was dropped from the final version.

If you have an issue with a particular library, please ask maintainers to drop support for "descriptions as comments" and remove usage of `getDescription`.
Meanwhile, you can continue to use v15 since it contains all the latest security fixes and is still supported.
