### ISSUE TITLE
[Feature Request] Add function `printDocument` for generating graphql file based on Document AST.

### ISSUE THREAD

**Issue by Industrial** [graphql/graphql-js#3531]
Hello.

I have created a little piece of software that takes a JSON Schema validated JSON structure of a list of "Models" and generates a `schema.graphql` and a `document.graphql` file which can then be used with tools like `graphql-codegen`. It uses a standard approach for fetching / changing models with the methods `show`, `list`, `create`, `update` and `remove` (since delete is a keyword in js I prefer remove..).

Currently, `graphql-js` supports printing a GraphQL Schema AST into a `string`. It does not support printing a GraphQL Document AST (which is only interfaces and not classes like the schema). The request is to add a function `printDocument` that prints the Document AST correctly.

I did [this](https://github.com/Industrial/test-ultra/blob/a63e8d73d02cecd7701d4bef49f1f6fb4d2016c6/src/lib/graphql/api-generator/GraphQLGenerator.ts#L363) but don't think it's a good idea to do this (there is an AST for a reason ..)

gr,

Tom Wieland / Industrial

p.s. Should I release the generator code as a NPM / Deno module? ([generator](https://github.com/Industrial/test-ultra/tree/a63e8d73d02cecd7701d4bef49f1f6fb4d2016c6/src/lib/graphql/api-generator), [models](https://github.com/Industrial/test-ultra/tree/a63e8d73d02cecd7701d4bef49f1f6fb4d2016c6/src/models), [example](https://github.com/Industrial/test-ultra/blob/a63e8d73d02cecd7701d4bef49f1f6fb4d2016c6/bin/generate-schema.ts))

**Comment by yaacovCR** [comment]
`graphql-js` currently supports:
1. printing a schema => string: `printSchema` from the `utils` module converts a GraphQLSchema object into a string 
2. printing a document, whether a schema or an operation => string: `print` from the `language` model converts any AST into a string

I am not 100% sure from the above if you are looking for `print` or if you are looking for conversion of a schema into a document rather than the string. If the former, I think the issue can be closed. If the latter, I guess the question would be the exact use case. You could always as a work-around call `parse(printSchema(yourSchema))`.
