### ISSUE TITLE
scalars with access to `context` re #2663

### ISSUE THREAD

**Issue by iambumblehead** [graphql/graphql-js#3539]
I'd like my graphql service to return internationalized error messages for invalid scalars

Following the example from this related ticket https://github.com/graphql/graphql-js/issues/2663, I'd like the service to do something like this,
```javascript
  parseValue: (value, context) => {
    const lang = context.get( 'accept-language' ); // somehow access express/koa language header
    const rounded = round(value);
    if (value !== rounded) {
      // throw new GraphQLError("Please provide a rounded number");
      throw new GraphQLError( i18nMessage( lang, 'please_provide_rounded_number' ) );
    }
    return value;
  },
```
Is there a known way to achieve the result described above? Because the scalar type does not have access to the context, I can't imagine how to achieve this.

**Comment by iambumblehead** [comment]
related https://github.com/apollographql/apollo-server/issues/4010

apollo documentation vaguely recommendation a mixture of plugins and hooks that are ineffective and require a lot of boilerplate code

**Comment by saihaj** [comment]
Yeah we don't really have a way to pass context to type system. You could try something with [`envelop`](http://envelop.dev) and hijack the results on after hooks in lifecycle methods

**Comment by iambumblehead** [comment]
context is widely needed and perhaps it should be passed through all parts of the response lifecycle, to be shared with any possible userland hooks that would need to modify or customize anything.

**Comment by IvanGoncharov** [comment]
@iambumblehead Thanks for providing the code sample, it makes super clear what you want to achieve.
Sadly scalars are used in many situations where context is not available (e.g. default values in SDL, introspection, etc.).

You can solve your use case by using `formatError` (or similarly named) callback provided by your framework and `extensions` field. 

```js
  parseValue: (value, context) => {
    const rounded = round(value);
    if (value !== rounded) {
      throw new GraphQLError({
        message: "Please provide a rounded number",
        extensions: { i18nMessage: 'please_provide_rounded_number' },
      });
    }
    return value;
  },
```

For the server part, I will use https://github.com/graphql/express-graphql for this example, but almost every other popular GraphQL server allows the same.
```js
app.use(
  '/graphql',
  graphqlHTTP(async (request, response, graphQLParams) => ({
    schema: MyGraphQLSchema,
    // ...
    customFormatErrorFn(error) {
      const formattedError = error.toJSON();
      
      const { i18nMessage } = error.extensions;
      if (i18nMessage != null) {
        const lang = request.headers['accept-language'];
        formattedError.message = i18nMessage(lang, i18nMessage);
      }
      return formattedError;
    }
  })),
);
```
Moreover, it's a generalized approach that allows you to provide internationalization for every error with passing context all around your code.
Plus you keep `i18nMessage` extension field in the server response which means better logging and debugging (since you can find similar errors without trying every language-specific message).

Does this solution solve your problem?

**Comment by iambumblehead** [comment]
@IvanGoncharov thank you for the response. This solution is similar to the one I ultimately did end up using.

**Comment by yaacovCR** [comment]
Great! Closing for housekeeping, please feel free to reopen as necessary.
