### ISSUE TITLE
Making sure the input data for resolvers is consistent

### ISSUE THREAD

**Issue by charypar** [graphql/graphql-js#38]
This is not really as much a problem as a question about practices. Playing with GraphQL I realised that argument resolutions rely on types always getting the same data structure from the parent resolver (unless you want to branch the logic in them).

Is there any clever way to ensure this? So for instance wherever I define an attribute of the `Image` type, I can make sure a resolver for that attribute eventually returns a data structure which attribute resolvers on `Image` can handle.

**Comment by leebyron** [comment]
Great question. This is something I would say is currently not easy to do in the JS reference impl but probably should be. I'll leave this open to track it.

In our PHP implementation in production at Facebook, we have a function that each type defines that simply checks to ensure the produced value correctly fits the type expected, so that resolver functions for the sub-fields can be written with more confidence.

**Comment by charypar** [comment]
So would a potential solution like the Facebook one look something like this?

```
const Thing = new GraphQLObjectType({
  name: "Thing",
  description: "It's a 3D thing!",
  validate: (it) => (it.width && it.height && it.depth),
  fields: ...
});
```

**Comment by leebyron** [comment]
Yes, graphql-js has a function like this currently called `isTypeOf`, I just need to wire it up in this way.
