### ISSUE TITLE
In GraphQL how to set WriteOnce functionality in specific property in the collection schema

### ISSUE THREAD

**Issue by sau3078** [graphql/graphql-js#3956]
Lets say I have one json file of any entity say test.json.

{
  "name": "TestLoan",
  "bsonType": "object",
  "graphQLTypeName": "TestLoan",
  "properties": {
    "_id": {
      "bsonType": "objectId"
    },
    "loanId": {
      "bsonType": "int"
    }
}
}

Let say I have loanId property inside my TestLoan entity and I am creating graphql schema from this json in my springboot graphql application.

I have mutation classes to update this TestLoan entity like TestLoanMutation to update single records and TestLoabManyMutation to update multiple records.

I have requirement if my loanId is null intially then I should be able to update it with any other non null value. If at any time loanId value is set then we can't update it to null or any other non null value means write once.

How its possible to do in Graphql ?

**Comment by yaacovCR** [comment]
It seems like something you would handle within your resolver code rather than within the type system. Unless you wanted to introduce two different types that each satisfy and interface, with one type also having a loan. I’m going to close this issue for now as it seems to be a general graphql question rather than related to the reference implementation within this repository.
