### ISSUE TITLE
Provide some mechanism for updating context (primarily after a mutation)

### ISSUE THREAD

**Issue by AndrewIngram** [graphql/graphql-js#407]
#### Scenario
My context object is populated at the start of the request with an authentication token. This authentication token influences what data is returned by the graph (as you might expect).

I'm browsing my website anonymously, looking at a list of products. I choose to sign-in by using a form that exists on every page. This form triggers an authentication mutation. A side-effect of this mutation is to somehow give me a new token which i'll be using for subsequent queries. Part of my mutation query is to refetch the data for the page i'm looking at (handled automatically by Relay), so that the list of products now includes information related to me (whether i've liked it, added it to my basked etc). The problem is that mutations only return a value, they have no means by which to update the context - which is necessary for the rest of the query to return the correct data.

#### Possible solutions

1. Push the concern back to the client, force a whole new query request to be made, or a page refresh on login/logout. Not ideal
2. Mutate the context object as a side-effect of the mutation resolve function. This seems pragmatic, but it doesn't feel particularly nice, and won't work if you're favouring the use of immutable objects.
3. Provide some mechanism by which a mutation can replace the context object for the remainder of the request.
4. Any others?

Sangria appears to solve this problem by allowing a context update to be one of several possible outcomes of any resolution function. The typical case of just returning a value or a promise appears to be implemented as a convenience shortcut around a more sophisticated resolution API. They actually talk about this very problem of Authorisation in their documentation: http://sangria-graphql.org/learn/#authentication-and-authorisation

**Comment by helfer** [comment]
@AndrewIngram in graphql-js you can just straight-up modify the context from the resolve function, which will achieve the goal you want.

**Comment by AndrewIngram** [comment]
I guess I'll have to wrap it up in a decorator so that it hides the nasty non-functional behaviour. I was hoping for a cleaner pattern though.

**Comment by leebyron** [comment]
I would strongly discourage using GraphQL to perform authentication - it's just not well suited for the typical challenge-response nature of a well designed authentication RPC like OAuth or others.

Context is designed to represent "the environment" at the time of a query - very commonly including who is authenticated. As Jonas pointed out, if you really need to modify this directly you could just do so, though ideally there are very rare cases where you need to do this.

If you would like a functional/immutable pattern that captures shared mutable state, check out the `atom` pattern: http://clojure.org/reference/atoms

**Comment by AndrewIngram** [comment]
@leebyron would it be possible to get a more detailed explanation of why GraphQL is a bad match for auth? If only because people are using it for this reason, presumably unaware that it's a bad idea. The Sangria docs specifically include it as an example, so I think there's a lot of confusion out there.

Other than the updating context issue (which i've tackled via direct mutation as suggested), logging in with GraphQL works well, especially in combination with Relay. After logging in, the current user changes, and any data in the graph which would be affected by the change is automatically refetched. By stepping outside of GraphQL, I can't see any way i'd be able to reproduce this automatic refetching behaviour - i'd be forced to do a complete refetch of everything.

**Comment by stubailo** [comment]
Confirmed - I hear about a lot of people who are implementing auth in GraphQL because they feel like they want all parts of their API to be using the same style. Personally I'm a fan of just using regular HTTP endpoints for auth and not putting it in GraphQL, so that I can reuse general auth tools instead of reimplementing everything on top of GraphQL, but it would be good to have some material about this.

**Comment by OlegIlyenko** [comment]
Sorry for the confusion :) I think I haven't anticipated it when I put together the auth example. I normally also prefer to handle auth outside of GraphQL. Most of the projects I work with use OAuth and there is already bunch or infrastructure code available for it.

In several recent discussions I noticed that people tend to implement "login" mutation field, but every time I encourage them to handle login and authentication outside of GraphQL, before query is executed. For instance one can get an OAuth bearer token from a header, authenticate client, and then pass a user as a context object to a GraphQL executor (in fact this is what auth example demonstrates as well).

The reason I included `login` mutation field in the example is __not__ because I would like to entourage user login via GraphQL mutation query, but because it was the most obvious and easy-to-understand example of `UpdateCtx` usage :) I believe that [`UpdateCtx`](http://sangria-graphql.org/learn/#actions) is very useful tool on it's own. I do agree that you rarely need and use it, but when you need it, then it's a perfect tool for a task at hand and there is normally no other alternative. Mutation of a context object in any form is not an option in my opinion - due to nature of execution mechanism it will undoubtedly introduce a race condition. `UpdateCtx` on the other hand provides a way to update a context object in an immutable way for nested fields (and sibling fields in case of mutation query). Every time I hear feedback about it from users of the library and see their use-cases for it, I get a confirmation that it was a right choice to add it. 

I will update the docs to make this point clear and avoid confusion :)

**Comment by MohGanji** [comment]
> @AndrewIngram in graphql-js you can just straight-up modify the context from the resolve function, which will achieve the goal you want (that's basically option 2 you mentioned). That's perfectly fine imho, because mutations happen serially.

Actually, although this was not a clean solution, I tried it and it is not working for sub-fields. I change the context inside the resolver function of one of the fields in the return value, but the context still contains the old value in sub-fields inside.
