### ISSUE TITLE
Make sub selections optional unless explicitly defined otherwise

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphql-js#410]
Currently, all mutations have to return a value ~~, even if it's a boolean~~ if it's an object. That makes sense, because mutations are loosely described as "a write followed by a read". But there are some cases where that read isn't necessary, like analytics, user patterns, tracking, etc.

Using the example I found from a [similar issue on SO](http://stackoverflow.com/questions/34075018/graphql-mutation-without-sub-section):

```
mutation _ {
    updateCurrentUser(fullName: "Syava", email: "fake@gmail.com") // ERROR no sub selection...
}
```

I'd argue that this should be valid because the `type` is `UserType`, and GraphQL types have the loose definition of "optional by default". If I wanted to require a return value, i could set `type: new GraphQLNonNull(UserType)`, which in the current version is redundant AFAIK.

Since a mutation is nothing more than a `Field` with some args, the following could also apply to other fields that return objects, or a rule could be put in place to only apply to fields within `RootQuery, RootMutation, RootSubscription`. Personally, I'd say apply it equally to all & if folks want to require a sub selection, they can do so by wrapping the type in a `GraphQLNonNull`.

This issue equally affects subscriptions, since they will likely never return an object that fits into the `type` interface, but rather a) open a connection & return values from there, or b) return an observable. So conforming to optional sub selections would seem to pave the way for subscriptions.

**Comment by stubailo** [comment]
I guess the tension here is that the GraphQL query syntax assumes the only reason to query a field is to receive a value, so if you don't ask for any actual data (no sub-selection), then it assumes something is wrong. In this case, the field is queried for a side effect, so it makes sense to have it even though you're not interested in the result value.

Perhaps this should be restricted to fields that are queried for side effects? I think this only includes mutations, because don't subscriptions also need list the fields that should be sent in the subscription results?

**Comment by mattkrick** [comment]
correct me if i'm wrong, but in graphql a query is just a field like any other, which means we'd have to introduce specific logic for a field that's found within the schema's root mutation.

I'm proposing the following for a field `updateUser` with `type: User`
```
// no error
updateUser(name: "foo") 
```

For a field `updateUser` with `type: new GraphQLNonNull(User)`
```
// error
updateUser(name: "foo") 
```

For both, the following would still be an error:
```
// error
updateUser(name: "foo") {} 
```

**Comment by piotrblasiak** [comment]
Any updates on this? The norm, especially if you want to support Relay is to return an object and not a scalar after a mutation. But if you want to use Apollo, you won´t need to access the clientMutationId and this could skip the response from the mutation entirely. Now I have to add a "dummy" field to mutations both on server and client side.

**Comment by stubailo** [comment]
Yep, although it might be reasonable to add an object return type anyway in case you want to add fields there later without breaking backwards compatibility!

**Comment by piotrblasiak** [comment]
Exactly - both for that reason and for Relay support it makes sense to have a return type even if not all clients care about it, so not all queries should be required to.

**Comment by leebyron** [comment]
Closing this aging issue, but I agree with @stubailo's recommendation.

Returning an object type from a mutation is always a good idea since in the future it's highly likely that some client will want to read after a write and converting from a boolean to an object would be a breaking API change. If you want to support a case where clients don't request anything other than whether the mutation succeeded, then I recommend a field like `didSucceed: Boolean!` in that resulting object type.
