### ISSUE TITLE
Add non-breaking whitespace (/u00A0) as an ignored tokens

### ISSUE THREAD

**Issue by asiandrummer** [graphql/graphql-js#413]
I just came across a [GraphiQL](https://github.com/graphql/graphiql) user who has a query that throws an error saying GraphQL character stream cannot advance - debugged it and found out this guy had an non-breaking whitespace (/u00A0, code 160), which neither [codemirror-graphql](https://github.com/graphql/codemirror-graphql) nor `graphql-js` recognized as a valid ignored token. Should we add this character to the lexer `positionAfterWhitespace`?

**Comment by leebyron** [comment]
I'm curious to know more about the case - did someone write in with it? Typically NBSP existing in a query body is a sign that something else has gone wrong since there's no way to type one, typically it's an early sign that something has gone wrong with formatting a document - like maybe it went through MSWord or something, often when NBSP appear, other characters have also been altered in a way that could lead to unexpected results, so it was an intentional decision to exclude it from the spec and the implementing libraries.

I think if there was a clear convincing reason for adding it into the spec we could consider it, otherwise I think it's best to stay conservative.

**Comment by asiandrummer** [comment]
I think this happened when the user copied and pasted the query body from another editor (like MSWord and/or Emacs). Staying conservative makes sense within `graphql-js` - maybe `GraphiQL` or the online parser powering `GraphiQL` needs to handle this case.

**Comment by asiandrummer** [comment]
Handling from GraphiQL - closing issue since it's no longer related
