### ISSUE TITLE
Module not found: Can't resolve 'graphql/language/printer.js'

### ISSUE THREAD

**Issue by lisahns** [graphql/graphql-js#4179]
Hello there :)

We are using graphql/language/printer.js like this in an NPM module that is used by several applications:
```
Application A (shouldn't need import graphql/language/printer.js)
    <-- NPM Module A (has import graphql/language/printer.js)
```
```
import { print as getGraphQlQuery } from 'graphql/language/printer';
const query = getGraphQlQuery(GetAllEpisodes); 
```
Now, with applications consuming that package we get this error when building the application:
```
#23 54.70 Failed to compile.
#23 54.70
#23 54.70 ./node_modules/.pnpm/@package@38.1.0_@ace@1.5.0_axios@0.28.1/node_modules/package/dist/services/content-inventory/get-all-episodes/index.js
#23 54.70 Module not found: Can't resolve 'graphql/language/printer.js'
#23 54.70
#23 54.70 <https://nextjs.org/docs/messages/module-not-found>
#23 54.70
#23 54.70 Import trace for requested module:
#23 54.70 ./node_modules/.pnpm/package@38.1.0_@ace@1.5.0_axios@0.28.1/node_modules/package/dist/index.js
#23 54.70 ./src/pages/watch/sitemap_episodes.xml.tsx
#23 54.70
#23 54.70 ./node_modules/.pnpm/package@38.1.0_@ace@1.5.0_axios@0.28.1/node_modules/package/dist/types/generated/graphql/muninn.js
#23 54.70 Module not found: Can't resolve 'graphql-tag'
#23 54.70
#23 54.70 <https://nextjs.org/docs/messages/module-not-found>
```
The first idea to solve this would be to install GraphQL in the app, but we don’t want to add to the bundle size just to use this function. Should this printer function be maybe be included in the bundle?

This could also be related to this issue https://github.com/jasonkuhrt/graphql-request/issues/214

**Comment by JoviDeCroock** [comment]
I mean, typically you would mark `graphql` as a peerDependency, this way any usage of said package can be shared between application and library. Which de-duplicates module usage (bundle-size win) and ensures you always use the same version of the AST. If you really think there is no need for these assurances you could bundle in the function.

**Comment by soundstep** [comment]
Hi there, Thanks for the prompt answer. I'm working with @lisahns.

As the import is part of the NPM module, why wouldn't the dependency not be bundled like it happens with any other dependency? If any NPM package is added as a dependency and the dependency is used, any bundler like vitejs or others will include the code used unless specified otherwise.

Do we need to force the inclusion for some reason? It feels like we're missing something somewhere as it is the only import that reacts this way.

We'd be happy to include this function and bundle in the NPM module as if I recall well, it is very small. We don't want to add a required dependency on all the applications using this NPM module for something that small.

Does that make sense?

**Comment by JoviDeCroock** [comment]
I mean, bundlers use differing heuristics, i.e. a lot of them will look at the bundle-target and see what the `dependencies`/`peerDependencies` are where `peerDependencies` will never be bundled in, this has absolutely nothing to do with this package 😅 

Just re-iterating this, having `graphql` be a peer-dependency is often preferred either way, this will enable people to use `graphql` while using your package without having the functions that you are bundling in be duplicated. The function might be small but there is more to the function, i.e. you will bundle `Kind`/`visit`/... and any operation of GraphQL v15/v17/... might not work while during `peerDependencies` it would work.

**Comment by soundstep** [comment]
> Just re-iterating this, having graphql be a peer-dependency is often preferred either way

A few things about that.

We cannot put every single dependency as a peer dependency, this is not happening :)

Another point to clarify is that we are importing `graphql/language/printer.js` and not `graphql`.

A bit of context, `graphql` is used under the hood with [graphql/codegen](https://the-guild.dev/graphql/codegen/docs/getting-started), this is why the `graphql` library is in our codebase. We generated types and typescript operations with it.

The only way we found to get a string back for the typescript operations we're generating (I believe AST to string), a way also used by other people who have the same issue, is importing this `graphql/language/printer.js` file directly.

Now, this may not be a valid thing to do as there are no `exports` in your `package.json` for this file. 

<details>

<summary>graphql package.json</summary>

<img width="684" alt="Screenshot 2024-09-02 at 17 02 13" src="https://github.com/user-attachments/assets/8474bf73-a07b-4f43-8b7f-c75231613519">

</details>

NodeJS can access files from the root of its package, that's why it works, but unless I'm wrong that is more of a CommonJS thing, ideally an ESM export should describe its [exports](https://nodejs.org/api/packages.html#exports-sugar), or at least in my experience.

I think it may be the lack of this `exports` that may mess up the bundler, this is a wild guess at the moment but I'm trying to understand why only this import behaves differently. Something like:

```json
"exports": {
  "./language/printer": {
    "types": "./language/printer.d.ts",
    "default": "./language/printer.js"
```

So, is it an appropriate and intended way to access this `graphql/language/printer.js` in this manner?

Would there be a better way of doing so?

**Comment by JoviDeCroock** [comment]
I mean, you can rely on tree-shaking and import it from the root as well. That being said, this isn't really a graphql issue at this point, maybe a discussion for discord or GH discussions.

I am not advocating for putting everything in peerDependencies, only the ones that are _dangerous_ when duplicated.

**Comment by soundstep** [comment]
@JoviDeCroock Thanks for looking into this, [cross-posting to a new issue](https://github.com/dotansimha/graphql-code-generator/issues/10128) to [graphql/codegen](https://the-guild.dev/graphql/codegen/docs/getting-started), the ones using `graphql`, to get some advices.
