### ISSUE TITLE
Passing additional arguments to the input results in an error with no error message.

### ISSUE THREAD

**Issue by bnewtonius** [graphql/graphql-js#426]
Using version 0.6.1, when extra arguments are passed into an input it gives an empty errors array with no error message.

Example:

```
const Query = new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
        section: {
            type: Section,
            args: {
                id: {
                    type: new GraphQLNonNull(GraphQLID)
                }
            },
            resolve({db}, {id}) {
                return db.get(id);
            }
        }
    })
});
```

with query:

```
query={
    section(id:"someId" extra:"bar") {
      ...
    }
}
```

Returns this:

```
{
    "errors": [
        {}
    ]
}
```

**Comment by bnewtonius** [comment]
This also seems to be happening for other error conditions, like a required argument not being provided.

**Comment by bnewtonius** [comment]
I believe the problem is that the GraphQLError object that is being created is not getting JSON.stringified correctly on the way back out when using something like Hapi. In graphql.js, if you change the validationErrors bit to something like this it works:

```
    if (validationErrors.length > 0) {
      resolve({ errors: validationErrors.map((error) => error.message) });
    } else {
      resolve((0, _execute.execute)(schema, documentAST, rootValue, contextValue, variableValues, operationName));
    }
```

**Comment by bnewtonius** [comment]
Another option is to add this to the error/GraphQLError.js object so that it returns the error message when it is stringified:

```
    _this.toJSON = function() {
        return _this.message;
    }
```

**Comment by leebyron** [comment]
Could you provide some additional information about how you're using GraphQL? Are you using `express-graphql` or just calling the `graphql` function provided by this library directly?

`GraphQLError` is a subclass of JavaScript's `Error` and behaves the same with respect to JSON.stringify:

```
> JSON.stringify(new Error('this is an error'))
'{}'
```

That at least explains the behavior you're currently seeing.

This was originally done to provide GraphQL http services the ability to have direct access to these Error instances to derive as much interesting information from them as they like, or to filter them down or include more information in a response.

However I agree with you that this seems like it's not quite what we want - really we want to endow GraphQLError with some better JSON stringification behavior so that when you do nothing but JSON.stringify the result of `graphql`, that you'll get something that adheres to the spec.

**Comment by leebyron** [comment]
I attached a PR which should improve this behavior, but feel free to continue conversation on this issue.

**Comment by bnewtonius** [comment]
Thanks! In hindsight I could have attached the toJSON to the Error prototype. I like the approach you took though.
