### ISSUE TITLE
Exposing a simple list of the selection set in the resolve function

### ISSUE THREAD

**Issue by papigers** [graphql/graphql-js#458]
Hey,
One of the steps that are required to support querying databases using GraphQL, is to expose the required selectionSet in the resolve functions. That way, users could use that to project only the required fields, thus optimizing the database's query performance and minimizing the network traffic between the GraphQL server and the DB server.

For example, for the following query:
```
{
  user(id: 1) {
    name,
    email
  }
}
```

I would get this as an argument for the resolve function on the user field in the GraphQL Schema: `[ 'name', 'email' ]` (or something similar). This way I could project only those fields from the DB query.

I realize I can access the "root" selectionSet on the fourth paremeter (`operation.selectionSet`) in the resolve function, but this can get a bit messy for complex query. I'm looking for a way to expose only the required selection: under the user's `resolve` I would get only the selected user fields, and under "whatever"'s `resolve` I would get only "whatever"'s selected fields and so on...

I realize that supporting databases isn't your top priority right now, but I'm just looking for directions, maybe I'd could implement this on my own somehow.

**Comment by robrichard** [comment]
@papigers I created a package called [graphql-fields](https://www.npmjs.com/package/graphql-fields) that does something very similar to what you describe.

**Comment by leebyron** [comment]
I definitely suggest the approach taken by `graphql-fields` if this in the information you're looking for.

I would also suggest you consider performance tests for larger real-world queries under that assumption - what I've found is that querying an entire row (or at least the common subset available) can often result in *improved* global performance due to the opportunity for batching and caching when multiple values or types of values are fetched more than once during the operation of a query.

A lot of this may depend on your exact use case, schema, or database config, so YMMV.
