### ISSUE TITLE
Would it be possible to add custom security attributes in GraphQL schema?

### ISSUE THREAD

**Issue by vonwao** [graphql/graphql-js#492]
I'm trying to figure out how to implement a security layer for a GraphQL system.  Most of the time, you would want to check security in the resolve functions.  However in some cases it would be nice to have a declarative system.  For example:

```
const userType = new GraphQLObjectType({
  name: "user",
  fields: () => ({
    userName: {
      canRead: function() {return true},
      canWrite: function() {return context.userId == this.ownerId},
      type: GraphQLString,
    },
    userRating: {
      canRead: function() {return true},
      canWrite: function() {return false},
      type: GraphQLFloat,
    },
  }),
});
```

Of course this would require wrapping query resolve functions.  And for mutations, I'm not sure, but maybe one could automatically generate CRUD mutations based on a schema like this. 

I'm not even sure if custom attributes in the schema are allowed.

Something like this could also be used for input validation.

**Comment by stubailo** [comment]
Here's what the new GraphQL.org best practices section says on the topic: http://graphql.org/learn/authorization/

Basically, permissions logic should go in the business logic layer underneath the schema, not in the schema and resolvers themselves. That way, you can think about the objects in your data model rather than needing to secure all of the resolvers separately.

**Comment by vonwao** [comment]
Understood.  This generally makes sense, but I still wonder if custom attributes and interceptors in general would be useful, so I made a created a new issue that is more precise (https://github.com/graphql/graphql-js/issues/493)
