### ISSUE TITLE
There is no @types/graphql for typescript 2

### ISSUE THREAD

**Issue by Asing1001** [graphql/graphql-js#503]
Will there have @types/graphql for typescript 2 ?

**Comment by DxCx** [comment]
you can use [typed-graphql](https://www.npmjs.com/package/typed-graphql)

**Comment by kylecordes** [comment]
Would be great to see these types put in the types mechanism, though the workaround above does work well.

**Comment by whitecolor** [comment]
It would be great if this types come with graphql package together, though `@types/graphql` will be ok.

**Comment by leebyron** [comment]
Closing this. We're not committing to maintaining a separate typescript definitions file for this repo, however I encourage using definitely-typed and typed-graphql as community efforts.

**Comment by kylecordes** [comment]
To help anyone else who arrives here from a search: the typed-graphql work is now published as part of the TS2 types mechanism, you can ise the standard ```npm i @types/graphql```.

(Because the GraphQL doesn't maintain these though, it's likely there will be some latency between future GraphQL updates and typing changes.  I am just a passerby who uses these things, I'm not involved neither project, though I do have a dream that someday a bridge could be built between the different communities adding types to JavaScript in different ways.)

**Comment by whitecolor** [comment]
@kylecordes it seems npm's `typed-graphql` https://github.com/nitintutlani/typed-graphql (1.0.2) and `@types/graphql` (0.7.1) are a little bit different things inside, is it supposed be this way?

**Comment by kylecordes** [comment]
@whitecolor It's not clear to me what the differences are and why. I'm just a passerby trying to fill in some missing bits to help future GraphQL beginners who land here. Maybe the people who published these bits will pop up with an explanation of the provenance and differences. ```@types/graphql``` appears to arrive from the DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/graphql .

**Comment by whitecolor** [comment]
Ok, typings seem to have a like parts but has some differences. I've asked it here https://github.com/nitintutlani/typed-graphql/issues/32
