### ISSUE TITLE
Viewer concept for Mutations

### ISSUE THREAD

**Issue by ashah888** [graphql/graphql-js#510]
Is it a good practice to have a viewer for GraphQL mutations? Theoretically this makes sense to me as some mutation end points shouldn't be possible if you are not logged in, etc.

But when I see examples on the web, I only see implementation of GraphQL viewers for queries. For mutations, I do not see any implementation of viewers. For example, the GitHub API doesn't have a viewer on top of all their mutations.

**Comment by stubailo** [comment]
I don't think this issue tracker is the correct place to talk about these questions, but I've answered your question on Stack Overflow: http://stackoverflow.com/questions/39938560/graphql-viewer-for-mutations/39939747#39939747

The TL;DR is, there is no reason to use `viewer` in GraphQL.js, since you should do authorization via the `context`.
