### ISSUE TITLE
introspectionQuery cant work 

### ISSUE THREAD

**Issue by ifelsee** [graphql/graphql-js#515]
Here is my code 
```javascript
var introspectionQuery = require('graphql/utilities').introspectionQuery;
var request            = require('sync-request');
var response = request('GET', graphqlHubUrl,{
    qs:{
        query: introspectionQuery
    }
});
```
I get an Error `Module build failed: Error: Invalid introspection data supplied to `getBabelRelayPlugin()`. The resulting schema is not an object with a `__schema` property. `
then i check code and found something make this error 
I test by [http://graphql-swapi.parseapp.com/](http://graphql-swapi.parseapp.com/) and
[https://www.graphqlhub.com/playground](https://www.graphqlhub.com/playground)
```javascript
//graphql-js/src/utilities/introspectionQuery.js
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
// HERE IS IT! the `locations` make query error , and delete this can work well
        locations
        args {
          ...InputValue
        }
      }
    }
  }
```

all query
```

  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }

```

**Comment by stubailo** [comment]
Perhaps you're passing in an object that looks like `{ data: { __schema: ... } }` and you just need to unwrap the `data` property?

**Comment by robzhu** [comment]
Hey @ifelsee thanks for opening this issue! You're getting this error because you are executing a modern introspection query that asks for the _locations_ field on the directive type, but the GraphQL servers you're hitting are running an older version from before the _locations_ field was added. 

We added support for directive locations [here](https://github.com/graphql/graphql-js/commit/e89c19d2ce584f924c2e0e472a61bb805ce260d4). 

If you're just using these two GraphQL endpoints for testing and have control over your own GraphQL endpoint, upgrading to a newer version of GraphQL-js (>0.5.0) will support the _locations_ field on directives. If this workaround is sufficient, please go ahead and close this issue.

I will followup to see if we can update the swapi example to a newer version of GraphQL-js. As for graphqlhub, there is already an open issue: https://github.com/clayallsopp/graphqlhub/issues/37.

**Comment by ifelsee** [comment]
@robzhu Very useful! Thank you for your answer
