### ISSUE TITLE
Fragments don't match dynamically defined interface implementations

### ISSUE THREAD

**Issue by charypar** [graphql/graphql-js#55]
This is a total edge case, but here goes: In my current server implementation I need to support two backends and decide which one to use every time a run a query. So what I did was parametrise all types by the backend they are supposed to use. I made sure there is always a single instance of a type for a particular backend, but the side effect of this is the types don't all get defined *before* running any queries. They only get defined when resolving an interface type. The original `resolveType` looked like this:

```javascript
new GraphQLInterfaceType({
  name: 'Content',
  ...
  resolveType: (value) => {
    return (value.item ? ContentV1(backend) : ContentV2(backend));
  },
}
```

Having a fragment defined like this

```
fragment Basic on Content {
	id
	title
	lastPublished
}
```

and then running a query containing

```
	somecontentV1 {
		items {
			... Basic
		}
	}
	somecontentV2 {
		items {
			... Basic
		}
	}
```
breaks trying to resolve the fragment on type `Content`. The reason is the possible type names caching in `isPossibleType` here:

```javascript
isPossibleType(type: GraphQLObjectType): boolean {
    var possibleTypeNames = this._possibleTypeNames;
    if (!possibleTypeNames) {
      this._possibleTypeNames = possibleTypeNames =
        this.getPossibleTypes().reduce(
          (map, possibleType) => ((map[possibleType.name] = true), map),
          {}
        );
    }
    return possibleTypeNames[type.name] === true;
  }
```
(<https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L439>)

If for instance the first match for a `Content` interface is `ContentV1`, it will get created, then a fragment gets matched which calls `isPossibleType` and caches a single possible type name - `ContentV1`. When `Content` resolves as `ContentV2`, the same thing happens on fragment resolution, but this time, the cache already exists, so although `ContentV2` is now defined, the fragment doesn't recognise it as a valid type name. As a result you get an empty object.

I fixed the issue by changing the `resolveType` to the following

```javascript
resolveType: (value) => {
  const v1 = ContentV1(backend);
  const v2 = ContentV2(backend);

  return (value.item ? v1 : v2);
}
```

that is, instantiating both types eagerly.

I'm not sure this is a common enough case to remove the optimisation, but it should definitely be mentioned somewhere in big bold type that all interface implementations need to be defined *at the same time*.

Thoughts?

**Comment by leebyron** [comment]
Sorry for the wait on this issue.

It looks like the issue is that your types are not well defined before running the schema. The assumption throughout the GraphQL engine is that once a `GraphQLSchema` is created, that it is sealed and immutable. This prevents issues where each run of a graphql execution could result in mutating the schema.

From your code sample here, it appears that calling `ContentV1` probably produces a new instance of `GraphQLObjectType` which is created at runtime after the schema is created and sealed.

Ideally either this `backend` value is something that can be known when you boot your server, rather than per-request so that you can define it in as you assemble your GraphQL schema, or you should define it as part of the `rootValue` so that it's accessible from `resolve` functions throughout.

I'll ensure as we write documentation that we make it clear that once a `GraphQLSchema` is created, it's not to be altered.

**Comment by charypar** [comment]
I assumed immutability is the case. The only reason I did this was I didn't know about the ability to pass the execution context into a graphql call and use it in observers. Forgot to come back here and close it.

Hopefully this will come in handy to someone in the future. :)
