### ISSUE TITLE
Auth via viewer vs context

### ISSUE THREAD

**Issue by daviskoh** [graphql/graphql-js#571]
Getting a lot of mixed signals from online resources, docs, people on Stackoverflow, etc on whether it is preferable for a user of a graphql API to be authed via the `viewer` pattern 

```
query($token: token) {
  viewer(token: String) {
    name
  }
}
```

or via the context object of a resolve func.

Which is it?

**Comment by leebyron** [comment]
`viewer` is an anti-pattern in GraphQL APIs, so is authenticating via GraphQL. The authorization value `$token` should instead be some part of your network access protocol, not part of GraphQL - otherwise you could run the risk of leaking sensitive auth data when logging queries or reporting errors.

Typically we see auth done via OAuth, JWT, or even HTTP Basic Auth.

The primary purpose of the `context` value is to reference the currently logged in session so that you can do access-control correctly at any point during a query.

**Comment by koistya** [comment]
@leebyron what naming convention would you recommend for a field representing a currently authenticated user, "me" or "viewer"?

**Comment by wincent** [comment]
At FB we effectively use both:

- `viewer` is a root field that represents an `actor` (an "identity": could be a user, page etc) and an `account` (authenticating person).
- `me` is a root field that provides a shortcut to the `actor` (ie. it is equivalent to querying for `viewer { actor }`.

I don't think there's anything special about this pattern to recommend it; it's just a historical artifact of the way the schema evolved over time at FB.

About the only place where the convention is useful that I am aware of is that Relay knows how to handle `viewer` without any special configuration. In Relay Classic, it was useful to maintain the `viewer` convention to work around a number of limitations such as the inability to use connections as root fields; but those limitations no longer apply in Relay Modern.

**Comment by richardscarrott** [comment]
@koistya I've not seen "$me" as a value used before, I guess that's just replaced with `context.user.username` in the resolver? Seems like it could be a better pattern than `viewer {}` because it will also work with Mutations which cannot be nested, have you used it in mutations before? Aside, [I have a question open on SO related to this discussion](https://stackoverflow.com/questions/69816876/graphql-mutation-design-context).

**Comment by koistya** [comment]
@richardscarrott yes, `$me` in the [example above](https://github.com/graphql/graphql-js/issues/571#issuecomment-949872953) would be replaced with the value of `context.user.username`. I don't remember needing this pattern in mutations though. For example, calling `publish(id: "xxx") { ... }` will use `context.user` under the hood, to record which user published the article. Also, it's convenient to take advantage of `@appendEdge`/`@prependEdge` [directives](https://relay.dev/docs/guided-tour/list-data/updating-connections/#using-declarative-directives) in mutation fragments that update connections in the local Realy store.

**Comment by richardscarrott** [comment]
@koistya We have mutations where admin users are allowed to create records on behalf of another user, e.g. `createOrder(cartId: "123", userId: "user_234")` so we're trying out the token replacement pattern with both queries and mutations via a middleware fn e.g.

```ts
const tokens: Dictionary<TokenReplacementFn<any, any, Context>> = {
  $userId: (_, __, context) => context.user.id,
  $foo: () => 'BAR'
};

export const replaceTokens = tokenMiddleware({
  Query: { wishlists: tokens },
  Mutation: { createWishlist: tokens },
});

```

Then the auth layer doesn't have to worry about the tokens and can simply check whether the current user has permissions to act on the userId passed in.
