### ISSUE TITLE
Use parent in GraphQLUnionType's resolveType function

### ISSUE THREAD

**Issue by chentsulin** [graphql/graphql-js#587]
Think of there are some actions with its type and descriptor:

```js
const action1 = {
  type: 'SEND_MAIL',
  descriptor: {
    email: 'test@t.com',
  }, 
};

const action2 = {
  type: 'SEND_SMS',
  descriptor: {
    phone: '(+886)09xxxxxxxx',
  }, 
};
```

Typically, we will use switch or if else condition to recognize action type then do something differently. Here is the `Action` Type:

```js
const Action = new GraphQLObjectType({
  name: 'Action',
  fields: () => ({
    type: {
        type: new GraphQLNonNull(ActionType), // GraphQLEnumType
    },
    descriptor: {
        type: new GraphQLNonNull(ActionDescriptor),
    },
  }),
});
```

But when I try out with `GraphQLUnionType`, I can't find a way to get type information inside the descriptor. 

```js
const ActionDescriptor = new GraphQLUnionType({
  name: 'ActionDescriptor',
  types: [
    SendMailDescriptor,
    SendSmsDescriptor,
  ],
  resolveType: (data, context, info) => {
     // data, context, info is not very helpful here
     // data will be something like { email: 'test@t.com' }  
     // but determine type with GraphQLEnumType is better
  },
});
```

Any ideas? How can I access parent (action) in ActionDescriptor's `resolveType` function?

**Comment by leebyron** [comment]
It seems you could detect by the fields `email` or `phone` existing? Or perhaps I've missed the core issue?

**Comment by chentsulin** [comment]
In my cases, descriptors' fields may change over the time and types' descriptor may have same fields, so it's not ideal to detect them by field-based checks. If we need to change fields' checking logic in `resolveType` when one of types changed, it will become more and more difficult to maintain after our types grew. Ideally, we should follow open-closed principle, and avoid change resolveType frequently.

We want to support over ten types in our union in the future, so i think that will be plainful.

**Comment by khankuan** [comment]
Agree with @chentsulin. It seems to be risky to depend on field schema to determine object type. Did you find a resolution for this issue?

**Comment by khankuan** [comment]
@leebyron I find abstract types a unique case where it might be useful to have the type resolved by the source. Compared to other types, resolution is static via `type: TypeX`. What do you think?

**Comment by leebyron** [comment]
I think this is a pretty dangerous idea because graphql-js cannot ensure any guarantees about the source value in the context of resolving a type. You could only safely interact with the source value if you guaranteed that a particular abstract type only ever appeared as the return type of a field on *one specific* other type. That's definitely not something GraphQL ensures.

Also, if your schema does in fact have that guarantee, then there are plenty of other ways to enforce it so that it's safe to access the value outside of the graphql-js executor code. For instance with the original example the underlying `descriptor` object could have a `parent` field that would give you the save value as `source`, or more specific to that example's desired use case, the underlying object could also have a `type` field that duplicates it's parents so you could rely on it in `resolveType`. These would be considered implementation details of your server since you wouldn't have to expose fields on your GraphQL schema for these pieces of data.

**Comment by leebyron** [comment]
If the example stayed simple, then detecting fields in the underlying object could be a reasonable solution, though since @chentsulin mentioned that he expects more types over time and changing implementations to those types.

To solve this, I'd suggest adding a `type` property to the underlying objects which could be trivially matched in a `resolveType` interface, and would not need to be exposed as a GraphQL field.

**Comment by khankuan** [comment]
I feel that adding a type is a proper solution but not necessary a practical solution. It means that there is a hidden contract in graphql-js that wants all resolve data to have a `type` implementation, either its ORM models or classes or `_type` field in a plain object. I thought a great advantage of graphql is to allow resolution of data to be entirely up to implementation. However, with this hidden contract, all resolve methods would all need to be wrapped in a way that ensures that:
```
resolve(obj) {
  return someService.get(obj.typeId).then(data => decorateType(data, obj.type))
}
```
or
```
function someService.getWithType(obj.typeId)
```

Another example would be a situation where the type definitions is less strict at the model layer. For example, I might have an ORM entity `Animal`, or an external service, that only have the concept of `Animal` but does not define it's type. In my schema definition, I would like to differentiate between `Cat` and `Dog`, and I knew their types because they are derived from a CatLover or DogLover parent. I may not have the budget to immediately change my ORM schema, or perhaps for backwards compatibility reasons. If this relies on an example service, I may not have the access to change the external dependency. I am now forced to add an additional layer on top of the ORM/external service.

Instead of relying on graphql-js as the layer with great and strong type definition, I'll need to make sure that the data/service layer below is strongly typed as well. I think it is ideal but perhaps a barrier to adopting the technology.

**Comment by iocentos** [comment]
The signature of the `resolveType` functions takes the `info` object as the 3rd argument.
Inside the `info` there is the `rootValue` which contains the parent object you are looking for.
You can have a switch on the `into.rootValue.type` and return the appropriate type from there.
I am not sure though if it is a good idea to access the rootValue in that way?
Would that be a recommended approach?

**Comment by rijkvanzanten** [comment]
@iocentos seems that (on my end at least) `rootValue` is always `undefined` within info

**Comment by mnmistake123** [comment]
So, having the exact same issue. Did nobody find a way in the end without having to add the type inside of the child structure?

**Comment by fn0rth** [comment]
Same 👋
