### ISSUE TITLE
Returning an Error instance is treated as an error

### ISSUE THREAD

**Issue by also** [graphql/graphql-js#591]
I have a type

```
  type Error {
    name: String
    message: String
    stack: String
  }
```

When a resolver returns an instance of error, rather than satisfying the type it is treated as an error.

This is pretty surprising. I'd expect returning a rejected promise (or a list containing a rejected promise) to indicate an error, but the current behavior makes it difficult to expose errors as data via GraphQL.

**Comment by leebyron** [comment]
Right now this behavior is intentional because it allows for some nested values scenarios:

```js
resolve() {
  return [ "value", new Error("2nd value is missing"), "value" ]
}
```

And it supports a kind of FP style which avoids throwing but instead uses explicit `TValue | Error` style return values.

I think it would be surprising to see errors represented directly within the data of a payload, especially with this kind of type signature both since GraphQL already has a mechanism for handling errors and because sharing a local stack frame might leak implementation or security details from your API.

If you're returning real data that happens to model errors (as opposed to there being an error while querying data), I would just suggest not using javascript's `Error` type to do so. If you're wrapping a system that's already using the `Error` type for this purpose, then I'd suggest a function which converts it into something that graphql.js won't interpret as a runtime error, for example:

```js
{
  myErrorField: {
    type: ErrorType,
    resolve: obj => errorAsData(obj.myErrorField)
  }
}

function errorAsData(error) {
  if (error) {
    return { name: error.name, message: error.message, stack: error.stack };
  }
}
```

**Comment by jedwards1211** [comment]
@leebyron this is actually really cool because it will be convenient for sending field-specific error messages back to the client, since `graphql` collects them together into a list with `path` information. 

The only issue is this behavior seems to be totally undocumented and it caught me by surprise today too.  @also is right, this **is** pretty surprising (I spent 30 minutes in the debugger wondering what was going on before it dawned on me that `graphql` must be deciding to handle `Error`s that I return this way).  We should work on documenting it.

I couldn't find any mention of this behavior in any of the following places:
* https://facebook.github.io/graphql/June2018/#sec-Errors
* https://graphql.org/graphql-js/execution/#execute
* https://graphql.org/graphql-js/error/
* https://graphql.org/graphql-js/type/#graphqlobjecttype

**Comment by jedwards1211** [comment]
FWIW, using the following `formatError` function allows me to attach extra fields to the returned `errors`:
```js
function formatError(error: GraphQLError): any {
  const {locations, message, path, originalError} = error
  return {locations, path, ...originalError, message}
}
```
```graphql
  Mutation: {
    errorTest: () => ({
      foo: 2,
      error: Object.assign(new Error('This is a test!'), {code: 2}),
    })
  }
```
```json
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "errorTest",
        "error"
      ],
      "code": 2,
      "message": "This is a test!"
    }
  ]
}
```

**Comment by jedwards1211** [comment]
@leebyron Actually there's another problem with this -- only the first `Error` object gets returned, rather than all of them.  This is disappointing as I thought I was going to be able to use this to send back multiple custom field errors to the client.
```graphql
mutation {
  errorTest {
    foo
    bar
    error {
      message
    }
  }
}
```
```js

  Mutation: {
    errorTest: () => ({
      foo: new Error('blah'),
      bar: new Error('blag'),
      error: Object.assign(new Error('This is a test!'), {code: 2}),
    })
  }
```
```json
{
  "data": null,
  "errors": [
    {
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "errorTest",
        "foo"
      ],
      "message": "blah"
    }
  ]
}
```

**Comment by jedwards1211** [comment]
@leebyron 
> And it also supports a kind of FP style which avoids throwing but instead uses explicit TValue | Error style return values
This is an interesting point, but it also runs against the grain of JS error-handling conventions.  For instance, `asyncFunction().catch(e => e)` will **resolve** to the error, rather than rejecting.

**Comment by IvanGoncharov** [comment]
> Actually there's another problem with this -- only the first Error object gets returned, rather than all of them.

@jedwards1211 This is expected behavior for lists with non-null items:
https://facebook.github.io/graphql/June2018/#sec-Errors-and-Non-Nullability

> If a List type wraps a Non-Null type, and one of the elements of that list resolves to null, then the entire list must resolve to null. If the List type is also wrapped in a Non-Null, the field error continues to propagate upwards.

**Comment by jedwards1211** [comment]
@IvanGoncharov the example I gave is not using a list though, so why would that apply?

**Comment by IvanGoncharov** [comment]
> the example I gave is not using a list though

@jedwards1211 Too sleepy ATM 🛌
Probably answering emails before going to bed was a bad idea 😄 

> so why would that apply?

Can you please show SDL of you schema?
I suspect that both `errorTest` and `error` is non-nullable.
If so that this will apply:
> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

**Comment by jedwards1211** [comment]
Oh I see, yes the fields were non-nullable.
Still, if multiple errors get propagated to a parent field, graphql *could* include all of them in the response, instead of just the first error, right?

**Comment by IvanGoncharov** [comment]
@jedwards1211 Good question. 

> If the field returns null because of an error which has already been added to the "errors" list in the response, the "errors" list must not be further affected. That is, only one error should be added to the errors list per field.

This rule is extremely useful when you try to reverse the process and replace all null values (returned due to errors) with error object, which is common pattern for example in different graphql proxies.

Note: In general GraphQL errors designed to be development time errors or critical failures and not intended to be used for client-side validation.

**Comment by jedwards1211** [comment]
Yeah, I realize now I should just throw my own error  type for validation
