### ISSUE TITLE
Enforcing access rules on object types

### ISSUE THREAD

**Issue by calebmer** [graphql/graphql-js#609]
What is the recommended way to enforce access rules on GraphQL object types? Before resolving fields, I would like the opportunity to throw an error if a user is not allowed to access a type. This would protect against accidental slip ups where an object is visible somewhere in the API that the implementor did not predict. For example an object exposed through a Relay 1 `node` field. I basically want to be able to right the following function which gets executed before any of the fields on my type resolve:

```js
function checkValue (value, context) {
  if (value.ownerID !== context.viewerID)
    throw new Error('Viewer is not allowed to view this object')
}
```

Would `isTypeOf` work for this? Is it guaranteed to run every time before an object’s fields resolve? According [to the docs](http://graphql.org/graphql-js/type/#graphqlobjecttype) `isTypeOf` does not get the `context` object so perhaps it couldn’t work.

**Comment by leebyron** [comment]
This is part of the role of your `resolve` function. GraphQL APIs which define access rules do so via a `resolve` field which first checks if the viewer is allowed to see the resolved value before returning that value (typically returning `null` or throwing an error if not allowed to see).

It's important to think about this in terms of *values* and not *objects* because there are more than just GraphQL object types which likely need access rules defined, including scalar values.

A pattern that I've seen be really useful is placing access control next to where you use dataloader (or something like it). Dan Schafer talked about this in his React Europe talk from earlier this summer which is definitely worth a watch: https://www.youtube.com/watch?v=etax3aEe2dA
