### ISSUE TITLE
Graphql dynamic variables usage in postman

### ISSUE THREAD

**Issue by sudheerj** [graphql/graphql-js#643]
As per POC on Graphql language I'm trying to test various types of queries in POSTMAN.But I didn't find the way to add below dynamic queries in POSTMAN.If it is not supported by POSTMAN then how can we build local graphiql with our own schema.

Example,
   ```
query GetAccounts($filter: AccountsFilter) {
  accounts(filter: $filter) {
    account_name
  }
}
```

```
{
  "filter": {
    "region": "APAC",
    "code": {"in": [ "HK1", "SG1" ]},
    "account_number": {"nin": [ "1" ]}
  }
}
```

**Comment by olivierlesnicki** [comment]
Can you send a screen shot of your POSTMAN request?

**Comment by sudheerj** [comment]
Thanks for the response.Please find the below snapshot.
![image](https://cloud.githubusercontent.com/assets/3127317/21395997/986d58e0-c7d9-11e6-8db3-0519e128327d.png)

**Comment by robzhu** [comment]
Your HTTP post body format is incorrect. See this screenshot: 

![image](http://i.imgur.com/7GKThse.png)

You may also want to check out http://graphql.org/learn/queries/ for some more examples. For the general question, "how do I execute query X with Postman/cURL", you can construct/test your query in GraphiQL and then inspect the network tab's outgoing request format. From that, you'll know the HTTP request format that you need to form with other tools like Postman. 

Closing the issue, but feel free to reactivate if your problem is not addressed
