### ISSUE TITLE
schema-kitchen-sink.graphql has out-of-spec test case

### ISSUE THREAD

**Issue by swolchok** [graphql/graphql-js#650]
[Line 67 of schema-kitchen-sink.graphql](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql#L67) is `extend type Foo @onType {}`.  According to both [the prose schema language extension spec](https://github.com/facebook/graphql/blob/de5433206643b2ec9e87e18e142f2e630bfa05b9/spec/Section%202%20--%20Language.md) and [the full summary of the grammar](https://github.com/facebook/graphql/blob/de5433206643b2ec9e87e18e142f2e630bfa05b9/spec/Appendix%20B%20--%20Grammar%20Summary.md) from https://github.com/facebook/graphql/pull/90, this is ungrammatical:

`TypeExtensionDefinition : extend ObjectTypeDefinition`
`ObjectTypeDefinition : type Name ImplementsInterfaces? Directives? { FieldDefinition+ }`

At least one `FieldDefinition` must be included to match `FieldDefinition+` according to [the notation conventions](https://github.com/facebook/graphql/blob/de5433206643b2ec9e87e18e142f2e630bfa05b9/spec/Appendix%20A%20--%20Notation%20Conventions.md):
>A subscript suffix "{Symbol+}" is shorthand for a list of one or more of that symbol.

 I'm not sure if this is a bug in the (admittedly RFC) spec or the graphql-js implementation.

**Comment by swolchok** [comment]
Also applies to `type NoFields {}` on the following non-blank line.

**Comment by tcr** [comment]
Changing the parser from ["any" to "many"](https://github.com/graphql/graphql-js/blob/master/src/language/parser.js#L809) results in these tests failing:

* [type Hello implements World { }](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-parser-test.js#L168)
* [type Hello implements Wo, rld { }](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-parser-test.js#L188)
* [extend type Foo @onType {}](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql#L67) (as well as in [schema-printer-test](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-printer-test.js#L113))
* [type NoFields {}](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql#L69) (as well as in [schema-printer-test](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-printer-test.js#L115))
* [type Hello implements Bar {}](https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/buildASTSchema-test.js#L706)

**Comment by leebyron** [comment]
Thanks for the investigation, @tcr!

There's two directions we could go. One is to change this implementation from "any" to "many" as you suggest, the other is to change the language in the spec proposal from `Term+` to `Term*` (essentially, make the "any" implementation correct)

One benefit from the "many" approach suggested in the spec proposal is that schema text like `type NoFields {}` is intentionally non-parsing. That means that it's *not possible* to write an invalid schema where a type has no fields. However that also leads to a drawback of the "many" approach which is that the `extend type` may be extending in a way which does not add fields. The `extend type Foo @onType {}` example should be *possible* - it describes adding some metadata to a type via a directive, or `extend type Foo implements Bar {}` which describes how `Foo` should implement `Bar` but assumes `Foo` already defines the necessary fields.

I'm open to feedback about how to address this, but I'm leaning in favor of leaving this implementation as is, but changing the spec proposal to the "any" case to match, thus potentially allowing invalid schema text to be written, but not limiting otherwise reasonable use cases. The invalid schema text can still be caught by other systems - schema validation (which we already have baked into the schema constructor functions) as an example.

**Comment by wincent** [comment]
I think you're leaning in the right direction.

**Comment by leebyron** [comment]
I can also scope the change only to `ObjectTypeDefinition` - the other definitions don't apply to `extend type`

**Comment by tcr** [comment]
To summarize my understanding:

* `type NoFields {}` is undesirable but not yet defined as an error—you can still query it as `no_fields { __typename }` for example.
* `extend Type Foo implements Bar {}` should be allowed.
* `extend type Foo @onType {}` should be allowed, and by extension `type Foo @addFields {}` should be too.

While you could split `ObjectTypeDefinition` into separate cases for `extend` and regular `type` decls, I don't see the benefit of enforcing at the syntax level that a type has more than 0 fields. So changing the spec proposal to `ObjectTypeDefinition*` sounds reasonable to me.

**Comment by IvanGoncharov** [comment]
@swolchok @tcr It was fixed in https://github.com/facebook/graphql/pull/90/commits/bde02b9da4323eec50d72bf47e473f1add66a06d
By allowing allowing to omit curly braces, e.g. `type NoField`, `extend type Foo implements Bar` and `extend type Foo @onType`.

`graphql-js` was adapted to this change in #1117
So I think this issue can be closed.

**Comment by leebyron** [comment]
Thanks for following up on this, @IvanGoncharov! I definitely intended to mark this issue fixed with that set of changes.
