### ISSUE TITLE
Enums don't support non-alpha strings

### ISSUE THREAD

**Issue by WhitneyLand** [graphql/graphql-js#668]
It seems that enum values (strings) with non-alpha generate an error.  Is there any reason this shouldn't be valid?

                "kind": "ENUM",
                "name": "Salutation",
                "fields": null,
                "inputFields": null,
                "interfaces": null,
                "enumValues": [
                    {
                        "name": "MyEnumValue2.5%",
                        "description": null,
                        "isDeprecated": false,
                        "deprecationReason": null
                    }
                ]

**Comment by wincent** [comment]
Thanks for the question!

The spec calls for [enum values](http://facebook.github.io/graphql/#sec-Enum-Value) to be [`Name` tokens](http://facebook.github.io/graphql/#sec-Appendix-Grammar-Summary.Lexical-Tokens), ie: `/[_A-Za-z][_0-9A-Za-z]*/`, so "MyEnumValue2.5%" is invalid due to the period and the "%". A valid alternative would be something like `MY_ENUM_VALUE_2_5` or similar.

(In terms of why the spec is this way, in general the syntax is conservative/restrictive in what it allows in order to maximize the scope for integrations with tools, libraries, languages etc.)
