### ISSUE TITLE
Post resolve function

### ISSUE THREAD

**Issue by nicolasgere** [graphql/graphql-js#677]
Hello here, i have some question about a function for a post resolve of a graphQL list, i have implemented one in my version, the question is,
Is it conceptually correct to have that? 
The case was: 
I have an object A with a GraphQLList of an object B, but i want to filter that list of b by a "calculate" field in b.
Two solutions:
- Pre calculate the field in the resolve of the object A
- Calculate the field in B as i want, and add a post resolve function in A who filter the result

I dont know if it's clear? 
thanks a lot for that library

**Comment by leebyron** [comment]
Typically, you should only be calculating values as they are requested. If you pre-calculate the field in the resolver of field A, then you may have wasted work should field B never be queried.

I would suggest moving the filter argument to the B field if it applies there, rather than applying it to the parent A field.
