### ISSUE TITLE
Get list of required fields for child object.

### ISSUE THREAD

**Issue by miketamis** [graphql/graphql-js#687]
Give a query like 

```
hello  {
  world {
    a
    b
    d
  }
}
```

what would the easiest way to generate an array like ['a', 'b', 'd'] in the resolver for world.

i currently have something like

```js
info.fieldNodes.find(field => field.name.value === 'world').selectionSet.selections
  .map(selection => selection.name.value);
```

this does work for an example like the one above, but won't work for situations that use a fragment i.e.

```
hello  {
  world {
    a
    b
    ...DFrag
  }
}

fragment DFrag on World {
   d
}
```

That above expression would generate ['a', 'b', 'DFrag'], when I would want it to generate ['a', 'b', 'd']

is there a function that graphql-js provides to collected all the fields (or other package),
or would i have to write a function that looks up the fragment checks if the fragment is on the right type, and also do the same for inline functions.

**Comment by robrichard** [comment]
@miketamis I made this package to do what you describe: https://www.npmjs.com/package/graphql-fields

**Comment by wincent** [comment]
@miketamis: You have to recursively explore the fragments, "flattening" them as you go, which is what the package @robrichard links to does. Note that there should be some memoization here, because in the worst case you could end up re-traversing the tree over and over again at every node.

I'll close this out because you have a solution now,  although I'd still be curious to hear from you what your use case is here and why you want to do this.
