### ISSUE TITLE
template tag?

### ISSUE THREAD

**Issue by humanchimp** [graphql/graphql-js#711]
It seems like a template tag could be a nice API for using graphql in javascript.

Just spit-balling here, but it seems like something like this would be nice:

```javascript
const graph = graphql(schema);

graph`
{
  user(id: 1) {
    name
    age
    friends {
      name
    }
  }
}
`.then(...)
```

**Comment by stubailo** [comment]
This would be great to publish as your own package! Should be pretty simple, since it's just wrapping an equivalent API in graphql.

My main concerns would be that using GraphQL without variables, context, or root value is pretty limiting, and this API doesn't have any clear way to provide those things.

**Comment by humanchimp** [comment]
OK, I'll look into possibly doing something like this as my own project. Thanks!

**Comment by wincent** [comment]
Agreed that this is "user-land" kind of material well suited to living in a separate packages. There are already a few libraries out there that use template literals for similar purposes (thinking specifically of Relay, Apollo, etc, but I am sure there are others), but I haven't seen one with this specific shape before.
