### ISSUE TITLE
Including meta fields when querying the schema for an object type's fields

### ISSUE THREAD

**Issue by martinandert** [graphql/graphql-js#73]
I expect the following query on the star wars schema

```graphql
{ 
  __type(name: "Character") { 
    fields { name }
  }
}
```

to have the following output

```js
{
  __type: {
    fields: [
      { name: "__typename" },
      { name: "id" },
      { name: "name" },
      { name: "friends" },
      { name: "apearsIn" }
    ]
  }
}
```

but the `__typename` field is missing because it seems to be "dynamically evaluated". Shouldn't it be part of the list of available fields?

Also, in my opinion, querying for the fields of the root query object should also include the `__schema` and `__type` fields.

**Comment by leebyron** [comment]
This is good feedback.

There are a couple reasons meta fields are not returned as part of introspection, the biggest of which is just noise which tools need to around around.

However I think we're open to discussing this further.

**Comment by rmosolgo** [comment]
I also expected that, but I can see how `__typename` can be considered part of the executor, not part of the underlying schema.

**Comment by leebyron** [comment]
Closing this aging issue.

For posterity: it is intentional that the meta-fields (`__schema`, `__typename`) are not part of type definitions. We do this to avoid adding repetitive noise and because the fields were in fact never directly defined by the type.

Tools which use the schema that wish to be aware of metafields need to account for this. That's the tradeoff.
