### ISSUE TITLE
Confusion about undefined and null types

### ISSUE THREAD

**Issue by mlamp** [graphql/graphql-js#731]
Hello.

I'm trying to unset GraphQLObjectType's field by not providing field from resolve function. My expected result would be that when I'm querying that field it would be not set (because resolve gave undefined). Example what I mean, I have type field "test" on root query witch is type Test like so:
`type: new GraphQLObjectType({ name: 'Test', fields: { testField: { type: GraphQLString } } }),`
And resolve function for it like so:
`resolve: () => { return {  }; },`
While querying like:
```javascript
{
  test {
    testField
  }
}
```
I'm expecting to get result: `{ "data": { "test": {} } }` But actually I get
```javascript
{
  "data": {
    "test": {
      "testField": null
    }
  }
}
```
Is there a reason why graphQL adds nulls?

**Comment by timsuchanek** [comment]
So I only can speak for Sangria, the Scala implementation, there it would be the same.
To understand that behavior, you need to know 2 things:
1. The Resolver works top down
2. null is the `undefined` or `None` of GraphQL
3. The query defines the structure of the response

So the resolver goes top down and looks for `test`, when test is not there because you didn't provide it in `{}`, the resolver automatically sets all child fields to `null`.
That is actually expected behavior as a query should always specify the _structure_ of the response.
A client that does this query must be able to assume the fields `data.test.testField`, otherwise the whole idea of GraphQL wouldn't make sense 😃 
When we would just return `"data": { "test" : {} } ` the whole query doesn't make sense as a client now cannot trust the GraphQL typesystem anymore.
I hope that helped
