### ISSUE TITLE
rootValue vs contextValue

### ISSUE THREAD

**Issue by adriano-di-giovanni** [graphql/graphql-js#735]
Can you give guidelines and usage examples to clarify appropriate uses of rootValue and contextValue, please?

Thanks

**Comment by prozacgod** [comment]
Also the graphiql interface this was not documented well? IIRC, but the configuration object can be a function, which gets the req argument, I use another middleware to compose the schema and context, because I dog food the schema for "all access to external databases" I wrote a tiny session store that overlays graphql, and various other "adminy things" like creating new users, all done in the graph, or authorizing users... all done in the graph etc.

    app.use('/graphql', graphqlHTTP(
      (req) => {
        return {
          graphiql: true,
          schema: req['graphql'].schema,
          context: req['graphql'].context
        };
      })
    );

**Comment by leebyron** [comment]
Lots of great answers here, so I'll close this issue.

Generally, the context value is information that is useful at any point during query execution. A canonical example is the current logged in user. The root value represents the "top" of your metaphorical graph of data, and is useful to include functions or data to help resolve the root fields in your schema.
