### ISSUE TITLE
Request: Global Error Handler

### ISSUE THREAD

**Issue by thanpolas** [graphql/graphql-js#773]
Hello,

We want to enforce a global error handler across all our graphql mutations and queries so as to apply specific business logic before the error reaches the client. 

So far I have only come up with the [kadirahq/graphql-errors](https://github.com/kadirahq/graphql-errors/) package, which basically walks all the fields of all the type definitions and wraps the `resolve` method of each one.

Is that what we only have today? Am I missing something? Would you consider adding such a feature, a global error handler?

**Comment by baer** [comment]
There are a couple of issues on this project to explore different error handling. See https://github.com/graphql/graphql-js/issues/284 https://github.com/graphql/graphql-js/pull/402

I'm not completely sure what types of business logic you're talking about applying but the `formatError` option in [express-graphql](https://github.com/graphql/express-graphql#options) will catch and aggregate errors thrown during resolution. You can use that function to log or format before they reach the client.

**Comment by leebyron** [comment]
This is already possible! Thanks @baer for some pointers to how you can implement this.

Since this package does not deal with sending results to a client, then the expectation is that you would place any post-processing between the output of any calls to this package and before serializing and sending to a client.

For example, in express-graphql, as @baer explained, a global error handler can be provided as an option - [here is how that ends up being used](https://github.com/graphql/express-graphql/blob/master/src/index.js#L304-L309).
