### ISSUE TITLE
Map Types?

### ISSUE THREAD

**Issue by ericclemmons** [graphql/graphql-js#782]
Apologies if I missed this, but after searching for quite a while, I can't seem to find a means of accomplishing:

```graphql
type GraphQLFieldConfigMap {
  [fieldName: string]: GraphQLFieldConfig
}
```

(Example taken from: http://graphql.org/graphql-js/type/#graphqlschema)

For a real example, I'm trying to query for a whitelist of feature flags:

```graphql
me {
  features(features: $features) {
    active
    name
  }
}
```

The result being:

```js
me: {
  features: {
    "show-lightbox": {
      active: true,
      name: "Show Lightbox"
    }
  }
}
```

This use-case doesn't seem to be supported without syntax errors, AFAICT.

**Comment by wincent** [comment]
I think you could model this by making `features` return a `GraphQLList`. Then given a query like:

```
me {
  features(features: ["show-lightbox", "other"]) {
    active
    name
  }
}
```

You would get a response like:

```
{
  "me": {
    "features": [
      {
         "active": true,
         "name": "Show Lightbox"
      },
      {
         "active": true,
         "name": "Other"
      }
    ]
}
```

**Comment by ericclemmons** [comment]
@wincent That's what I have now, but was hoping to avoid.  That way we can have JSON-like lookups off of the key (e.g. `me.features.showLightbox`).

I'm cool with defining a custom schema to do this (with parsers & all), but dunno if this is possible...

**Comment by baer** [comment]
@ericclemmons I don't think you're going to find a way to return an object of a variable shape but there are quite a few ways to get the result you're looking for. 

**Use the solution above**

  Though it's not quite as succinct as `me.features.showLightbox` you can always write a little helper like `_.find(me.features, feature => feature.name === "showLightbox")` to do your lookup. 

**Write an Interface**

Though it's quite a bit more code, you could write an Interface + custom type for each feature flag. This would be pretty cumbersome if you had a lot of feature flags but in my experience, there should only be a handful at any time.

**Change your output**

If easy consumption is the name of the game you could change your Schema to be something like the following. If you did that you could do `me.features.authoized.includes(showLightbox)`.

```
me {
  features(features: ["Show Lightbox", "Drink Orange Juice", "Sell Bicycle"]) {
    authorized
    unauthorized
  }
}
```

```
{
  "me": {
    "features": {
      authorized: ["Show Lightbox", "Drink Orange Juice"]
      unauthorized: ["Sell Bicycle"]
    }
  }
}
```

**Move RBAC outside of GraphQL**
It sounds a bit like you're inching towards an [RBAC](https://en.wikipedia.org/wiki/Role-based_access_control) system. There have been a number of talks on how to do authn and authz with GraphQL and the general consensus is that the GraphQL schema isn't really the place for it. I'd suggest you check out some of the talks on Youtube, articles from the Appolo folks and the auth section of the docs for more info on this. In my personal experience I've found it incredibly useful to do authn with a gateway in front of GraphQL and then doing authz by passing a function through context (I this is a part of graphql-express not this package) so that I can do something like this at the resolver level:

```
{
  ...
  resolve: (parentData, args, context) => {
    if (!context.authn(["Show Lightbox"])) {
      throw new Error("What do you think you're doing? That's not allowed!")
    }
    return resolveData(parentData);
  }
}
```

**Comment by ericclemmons** [comment]
Closing because this violates GraphQL's schema architecture.
