### ISSUE TITLE
Suggest more languge agnostic schema definition

### ISSUE THREAD

**Issue by serle** [graphql/graphql-js#91]
It would be nice to define the schema definition in a language agnostic way e.g. xml so that the schema could be shifted between graphQL implementations. This could also one to use more mature implementations in the meantime.

**Comment by schrockn** [comment]
@serle We are actively work on this. Indeed we actually have a working version of a type definition DSL. We haven't really shouted about it yet because we are still finalizing details and spec. 

You can see the parser here https://github.com/graphql/graphql-js/blob/master/src/language/schema/parser.js and an example file here https://github.com/graphql/graphql-js/blob/master/src/language/schema/__tests__/schema-kitchen-sink.graphql
