### ISSUE TITLE
Throwing errors from parseLiteral

### ISSUE THREAD

**Issue by Cardinal90** [graphql/graphql-js#910]
After 0.10.1 throwing `GraphQLError` from `parseLiteral` function in a custom scalar type leads to unhandled promise rejection. Tracked it down to this commit: https://github.com/graphql/graphql-js/pull/883/commits/62619dfe7d3274628ad0ad7f7d91e0a42d4c0517#diff-e896d5930c71857fc9566b22defba666
Parsing has a try-catch block around it, but validation does not. Doesn't seem like it was intended, considering it says "refactor".

**Comment by helfer** [comment]
Just ran into this in https://github.com/apollographql/graphql-server/issues/381.

**Comment by exogen** [comment]
Definitely not intended as far as I can tell, considering the purpose of the refactor was to ensure that "internal errors throw and GraphQL user errors are returned within the GraphQL Result" – in this case, the purpose of throwing from a custom scalar type is to inform the user that they've provided invalid input. I noticed this because it's making a couple of my [graphbrainz](/exogen/graphbrainz) specs fail. /cc @leebyron

**Comment by tkiethanom** [comment]
+1 

Getting "Internal Server Error" when throwing an error inside of `parseLiteral`.

**Comment by LuisUrrutia** [comment]
Any news on this?

**Comment by leebyron** [comment]
Validate should always return safely and not throw. Is this still an issue? In the future please escalate by submitting a PR with a failing test case or better yet a fix.
