### ISSUE TITLE
Destructuring input type

### ISSUE THREAD

**Issue by Gregoirevda** [graphql/graphql-js#919]
Is it possible to destructure a mutation input type?
The problem is that I'm using a graphQL serverless backend, which generated a mutation that doesn't takes a User input, but each property separately.

I'd like to create an input in my front end, so I have a clear understanding of the input type, but I need to pass each property to the mutation. I therefore thought about destructuring...

```
  type User {
      bio: String!
      email: String!
      password: String!
      picture: String!
      publicName: String!
      username: String!
  }
  
  mutation createUser($newUser: User!){
      createUser({...$newUser}) {
          id
      }
  }
```

Is there a way I can achieve this please?

**Comment by leebyron** [comment]
It is not possible to do this in the GraphQL language.

I would suggest either restructuring your mutation to accept an input type instead of individual fields, or to change your mutation to accept multiple variables that align to each argument your mutation accepts rather than providing an input type.
