### ISSUE TITLE
buildASTSchema() should throw on encountering `extend` definition

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#922]
`buildASTSchema()` exists to parse a fully complete schema definition and produce a schema. However currently if it encounters an `extend` definition, or any other definition it does not use for that matter, it silently skips over it. This can lead to a confusing debugging situation.

Instead, `buildASTSchema()` should throw when it encounters a definition that it does not use, similar to how `execute()` throws if a the provided document contains any definition other than operations.

**Comment by OlegIlyenko** [comment]
Out of curiosity: is there something that prevents supporting `extend` in `buildASTSchema`?

For example this definition:

```graphql
type Queries {
  querySubset: QuerySubset
}

type Query {
  queries: Queries
}

extend type Queries {
  hello: String
}
``` 

Look semantically correct to me. When used in this form in may look a bit unusual, but the last definition could be loaded from a different file. From what I can tell, supporting `extend` does not have any downsides and provides more flexibility.

**Comment by leebyron** [comment]
That would be new behavior, but I'd also be happy to entertain PRs adding that as well. If so, the same change should probably be made in extendSchema if multiple extend statements are found, and care should be put into ensuring that the order in which the extensions are applied result in the same output.

**Comment by dyst5422** [comment]
I think this might be a breaking change for graphql-tools. I believe the way it currently does schema extension concatenates a number of schema language strings together and then pulls the extensions out to add them in a second step.

Would it make sense to warn on this instead of throwing?
Is there a specific reason `buildASTSchema()` shouldn't parse extensions?
Should there be a method that DOES handle extensions as well?

**Comment by kaushik94** [comment]
Hey I would like to chip in on this one. Can I first take up the issue of adding a warning? Then I will try to understand and help implement handling `extend` statement?

**Comment by viztor** [comment]
Does extend work now? @leebyron 
or do we expect them to work maybe in the future?

The upside I'm seeing is as such allowing people building graphql application to modularize their application schema

**Comment by IvanGoncharov** [comment]
> Does extend work now?

@viztor Not at the moment but I plan to implement it for `14.1.0` release.
Currently, `buildSchema`/`extendSchema` is under heavy refactoring with the goal to implement #1389.

**Comment by langpavel** [comment]
For usecase where somebody needs multiple files merge up to one AST I write this helper: https://gist.github.com/langpavel/9653b99afe993167fc4bacafbfcc7909
Feel free to use it as an example of implementation which merge `extend` types into defined ones. Of course *WITHOUT ANY WARRANTY* :-)

**Comment by aishwar** [comment]
Hello, appreciate the work all of you do here. Just curious, when is the fix for this expected to be released?

**Comment by IvanGoncharov** [comment]
@aishwar Thanks. 
Can't say exact date but I will try to include it in `15.0.0` that I plan to release next month.

**Comment by dandv** [comment]
I've been flipping around 10+ issues on this topic, and I'd like some clarification: does Object extension actually work [per the spec](https://graphql.github.io/graphql-spec/June2018/#sec-Object-Extensions) in the current version of this reference JS implementation, or is it [undocumented](https://graphql.org/learn/schema/) because it only partially works (i.e. schema can be defined, but extended fields can't be queried)? (To further muddy the waters, extending types is documented to work with [graphql-tools](https://www.apollographql.com/docs/graphql-tools/generate-schema#extend-types).)

If it does work, what am I doing wrong in [this example](https://runkit.com/dandv/graphql-extend-object---how-to-query-local-field) that I'm getting this error?
> GraphQLError: Cannot query field "salary" on type "Person".

**Comment by IvanGoncharov** [comment]
Current implementation already fully support extensions using `extendSchema` function:
```js
const { graphql, parse, buildSchema, extendSchema } = require('graphql');

let schema = buildSchema(`
  type Person {
    name: String!
  }

  type Query {
    person: Person
  }
`);

schema = extendSchema(schema, parse(`
  extend type Person {
    salary: Int
  }  
`));

var root = { person: () => ({ name: "John Doe", salary: 1234 })};

graphql(schema, '{ person {salary} }', root).then((response) => {
  console.log(response);
});
```

> If it does work, what am I doing wrong in this example that I'm getting this error?

Thanks for example 👍 
ATM, `buildSchema` silently ignore extensions and you need to use `extendSchema` for that.
This issue is about adding support for extensions in `buildSchema`.
