### ISSUE TITLE
Type that allows both Single and List objects in same query

### ISSUE THREAD

**Issue by terencechow** [graphql/graphql-js#938]
I would like to make a feature request for Single & List to be returned in the same query.

Hitting `/blog` and `/blog/:id` both return blog objects, but one shows up in a list and one shows up as an individual object. It seems like quite a lot of work to copy and paste essentially the same query just so that you can be able to return blog singular vs blog list

for example:

if my fields has:
```

blogs: {
    type: ...something that allows list or single of BlogType,
    args: { blogId: {type: GraphQLInt}},
    resolve: (_, {blogId}) => {
        const url = blogId ? `${root}/${blogId}` : root
        return fetch(url)
    }
}

```

Notice these 8 lines handle basically both list and singular? If I have to copy and paste this just so that I have both `blog` and a `blogs` query that is a lot of extra code. It's literally 100% more with no real change in functionality. The only thing different is the `GraphQLType` and the fetch url. As design books always say, encapsulate what differs to keep it dry.

If you want to keep graphql dry, it makes sense to allow this functionality

**Comment by robzhu** [comment]
I think it's simpler for the client to be able to count on blogs returning a list of [blog]. Otherwise, the client would have to check for whether the response was an array or singular item. Perhaps you can share examples of how the client would benefit from a change like this?

**Comment by terencechow** [comment]
Blogs as a route just represents a resource to me. What makes it return a list or a singular object can be defined by the query.

For example `blogs { name, id }` would return a list but `blogs(id: $blogId) { name, id}` should implicitly return one item since I'm searching by a unique id. As a client I would know this implicitly and this keeps things dry for every resource I am using. The alternative which I'm forced to implement is to have twice as many routes for every resource I'm using both on the client and at the graphql server.

Right now my client has a `blogQuery` and a `blogsQuery`. My graphql server also has blogs and a blog root query. Having multiple return types allow me to cut both code bases in half.

**Comment by robzhu** [comment]
Suppose the blogs type returned either a single blog or multiple blogs depending on the presence of the blogId argument. Since you're executing a the same query, the client will need to detect whether you're dealing with one or many blogs. If you haven't done so already, take a look at how the swapi demo does this: http://graphql.org/swapi-graphql

A query such as:
`
{
  allFilms(first: 1) {
    films {
      id
    }
  }
}
`
returns a collection of size one, not a single film. If I'm understanding your correctly, you would prefer it to return a single film?

**Comment by wincent** [comment]
There are no hard-and-fast rules here, but it's pretty common to have an equivalence between routes and queries: that is `/blog` maps to one query and `/blog/:id` to another. And these are conceptually different things: one is an index listing and the other is a "detail" or "permalink" view of a specific item. In most schemas I've seen, people want to assign these different concepts to different top-level fields as well (could be `blog` and `blogs`, for example).

If you really, really wanted to have just a single field, I'd suggest that it should probably always return a list anyway (even if it is a list of one, as would be the case for the permalink). You'll still need separate routes, separate queries too (because you have to distinguish between the index scenario where the arguments will be something like `first: 10` and a permalink scenario where the arguments would be `id: "slug"` or similar). Any complexity that you save on the client by doing this will just end up residing in another place (on the server in this case, in the code that distinguishes between these two calling conventions).
