### ISSUE TITLE
Using graphql client-side

### ISSUE THREAD

**Issue by gyzerok** [graphql/graphql-js#95]
Can you add a changelog with description of new features usage. [This commit](https://github.com/graphql/graphql-js/commit/6a6f1c3785df282cce857b72de09df5ddfae530f) looks like we can now use GraphQL on the client, but there is now good description on how to do it right.

**Comment by leebyron** [comment]
We keep a changelog at https://github.com/graphql/graphql-js/releases.

We're working towards some next milestones at the moment that commit plays a part in, and will be released to npm soon. When they are, I'll ensure the changelog is updated to reflect it.

Documentation is also something we're working on at the moment, so that should improve quite a bit in the near future.
