### ISSUE TITLE
Query.node field type must be Output Type but got: Node.

### ISSUE THREAD

**Issue by ablbol** [graphql/graphql-js#956]
Hi, I tried to upgrade to version 0.10.4 and 0.10.5 but started getting the following errors in both versions.  I don't see any problems in version 0.10.3. Any idea why?

Error: Query.node field type must be Output Type but got: Node.

Thanks

**Comment by AchrafBn** [comment]
I have the same error , did you solve it ?
 version graphql is :  0.9.6

**Comment by mattkrick** [comment]
check your yarn or npm lockfile & make sure there is only 1 version of graphql installed. `isOutputType` uses `instanceOf` instead of `constructor.name`, so if you have 2 versions of graphql installed, it likely grabbed the wrong version & will always return false. This could likely happen if you have a dependency that has graphql as a dependency instead of peerDependency.

**Comment by jonirrings** [comment]
check this
https://github.com/relayjs/relay-examples/issues/25

**Comment by leebyron** [comment]
This is almost always due to multiple `graphql` installs in the `node_modules` directory.

I'm working on improving the error messages for these cases
