### ISSUE TITLE
Flow Instructions?

### ISSUE THREAD

**Issue by bradennapier** [graphql/graphql-js#966]
Not really sure how to use flow with this package.  Can't find much information and reading source hasnt yielded results for me at this time.  

I get an error when trying to build my schema.  Not sure how to do this or what I might be missing here?

![image](https://user-images.githubusercontent.com/15365418/28548471-0b3c8d52-7089-11e7-8236-9bd3061aa00c.png)

**Comment by bradennapier** [comment]
I tried a different setup slightly and i get a whole new set of errors requiring things that I dont see even discussed

![image](https://user-images.githubusercontent.com/15365418/28549097-d91450a4-708c-11e7-9ba4-00ec0a527d9f.png)

Although I assumed GrpahQLSchemaConfig would be a type that was exported by the library itself - it seems that it is not and must be defined manually?

![image](https://user-images.githubusercontent.com/15365418/28549139-07a5d618-708d-11e7-869d-59bf2c2c71f6.png)

**Comment by bradennapier** [comment]
As additional information, I then import the Query and Mutation which look like:

```js
// http://graphql.org/graphql-js/object-types/
const Query = new GraphQLObjectType(
  ({
    name: 'DashOSQueryAPI',
    description: 'Root Query Schema',
    fields: () => ({
      legacyUser,
      user,
      dealer,
      project,
      system,
    }),
  }: GraphQLObjectTypeConfig<*, *>),
);

export default Query;
```

**Comment by leebyron** [comment]
Sorry for allowing this issue to sit, but I'm going to close it since it is aging.

Flow library definitions are included in the npm bundle, if you use flow then it should report mistakes in using the GraphQL.js API - I recommend looking at the definitions of functions (some IDEs will allow you to command-click to jump to them) for descriptions of how functions in the library expect to be called.
