### ISSUE TITLE
Client-side deserialization utility

### ISSUE THREAD

**Issue by asaf-romano** [graphql/graphql-js#986]
In our GraphQL js client infra we are implementing a utility for deserialzing custom scalars in server-returned result documents. The API looks roughly like this:

```js
function getResultDocumentSanitzier(clientSchema, customScalarTypeToSanitizer)
{
   // ...
   return documentResult => {
      // ...
      return sanitizedDocumentResult;
   };
}
```

Ant then it's used roughly like this:
```js
ScalarMapping = {
   DateTime: v => moment.utc(v),
   IpAddess: // ...
};

// ...
Client  = {
  // ...
  async query({ query /* ast */,  ....)
  {
     let { data: result } = ...query the server;
     const sanitize = getResultDocumentSanitzier(clientSchema, ScalarMapping); // cached
     return sanitize(result);
  }
}
```

The actual magic is done using the amazingly-powerful TypeInfo-flavored ast visitor in ``utilities`` along with buildClientSchema. This allowed us to support aliases and fragments.

Admittedly, the main driver for implementing this was the DateTime type which could be addressed in other ways (especially if it becomes a first-class citizen in the spec). However, in an isomorphic environment there are certainly other use cases, like ip-addresses and UUIDs.,

Given how generic this turned to be, I was wondering if you'd be interested  in including such a utility in the built-in set. We'd gladly send a PR.

**Comment by asaf-romano** [comment]
@leebyron, @wincent Is this something you'd consider including in the built-in utility belt?

**Comment by wincent** [comment]
This sounds like a feature that can be entirely independent of the core reference implementation (ie. it could be published as a separate NPM package) and my inclination is to think that it's better kept separate so that the reference implementation is closer to an "embodiment of the spec" than a "generally useful collection of GraphQL tools". Once you start going down the path of accruing useful functionality, it's difficult (and somewhat arbitrary) to draw the line where to stop. Once an idea or a concept becomes core enough that it makes it into the spec proper, *then* I think its appropriate to fold it into the reference implementation.

**Comment by leebyron** [comment]
Agreed, this would be a great community project. Go nuts!
