### ISSUE TITLE
GraphQL pre-approved queries

### ISSUE THREAD

**Issue by raderio** [graphql/graphql-js#998]
Dows graphql-java support pre-approved queries?

https://www.reddit.com/r/reactjs/comments/5aemkc/if_graphql_servers_are_only_going_to_accept/

**Comment by wincent** [comment]
Did you mean to file this against https://github.com/graphql-java/graphql-java @raderio?

**Comment by raderio** [comment]
Oh, I mean graphql-js of cource. Thanks.

**Comment by wincent** [comment]
@raderio: Yes, it supports "pre-approved" in the sense that it is a very low-level building block upon which you can build other things. At Facebook, we call these "persisted queries": as part of your build process, you save the queries to a database and have you client send up the query IDs instead of the query text itself. If you're using `graphql-js`, you have some business-specific layer that accepts the request, reads the query from the database (which could be anything: a SQL database, an in-memory cache, files on the file-system etc), then executes that query text using `graphql-js`. You could also consider caching the AST of the parsed text as opposed to reading it from the database and parsing it every time.

**Comment by raderio** [comment]
Thanks. Do you also know some good articles related to persisted queries?

**Comment by wincent** [comment]
@raderio: nothing official, but Scott Taylor blogged about it [here](https://medium.com/@wonderboymusic/upgrading-to-relay-modern-or-apollo-ffa58d3a5d59). [This](https://github.com/staylor/wp-relay-app/blob/be69460672af64eccddb4194bedf8b378ae31d0a/tools/persistedQueries.js) is his implementation.
